src/modals/PasteRowsInfo.vue
Reported at Transifex.
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
=> l10n: Fixed typo

src/modals/EditColumns.vue
=> add move column actions

src/Navigation.vue, src/pages/TablesOverviewView.vue
=> sort tables alphabetically

css/style.css, src/NavigationTableItem.vue
=> replace sidebar table icon

.eslintrc.js, .github/workflows/lint-eslint.yml, src/NavigationTableItem.vue, src/main.js, src/partials/TiptapMenuBar.vue, src/router.js
@datenangebot There are still some failures left, but as I've seen the icons on our call I left out fixing those since I thought you might have local fixes as well ;)
```
/Users/julius/repos/nextcloud/server/apps-extra/tables/src/partials/TiptapMenuBar.vue
103:24  error  "vue-material-design-icons/FormatBold.vue" is not found                     n/no-missing-import
104:26  error  "vue-material-design-icons/FormatItalic.vue" is not found                   n/no-missing-import
105:33  error  "vue-material-design-icons/FormatStrikethrough.vue" is not found            n/no-missing-import
106:38  error  "vue-material-design-icons/FormatListBulletedSquare.vue" is not found       n/no-missing-import
107:32  error  "vue-material-design-icons/FormatListNumbered.vue" is not found …
```
=> Run eslint on CI

lib/AppInfo/Application.php, lib/Capabilities.php
In addition to https://github.com/nextcloud/tables/pull/170
=> chore(capabilities): add some basic capabilities to the NC API

src/shared/components/ncTable/partials/TableCellHtml.vue
CSS adjustments and fixes we discussed today
#161
=> design(table): handle long text in text columns

lib/Reference/ReferenceHelper.php, src/reference.js
- return random cache key if debug mode is enabled
- load working components from vue-richtext
=> fix(reference): fix reference provider and widget rendering

src/shared/components/NcTile/NcTile.vue
=> fix: fix height and add overflow #269

src/shared/components/ncTable/partials/TableHeader.vue
closes #275
Signed-off-by: Florian Steffens <florian.steffens@nextcloud.com>
=> fix(permissions): use common permission matrix, closes 275

lib/Listener/UserDeletedListener.php, lib/Service/TableService.php
=> fix(cleanup): delete user data on user deletion, closes #271

.github/workflows/cypress.yml, .github/workflows/integration.yml, .github/workflows/phpunit-mysql.yml, composer.json, composer.lock, package-lock.json
Some other dependencies might get updated in the process, but no big changes
Closes #295
=> Set composer platform version to PHP 7.4 as it's the minimum compatible version for NC25

.devcontainer/devcontainer.json, .devcontainer/setup.sh, README.md
=> docs & devconatiner: add github devcontainer definition & update docs

cypress/e2e/tables.cy.js, src/shared/components/ncTable/mixins/columnsTypes/datetimeDateMixin.js, src/shared/components/ncTable/mixins/columnsTypes/datetimeMixin.js, src/shared/components/ncTable/mixins/columnsTypes/datetimeTimeMixin.js, src/shared/components/ncTable/mixins/columnsTypes/numberMixin.js, src/shared/components/ncTable/mixins/columnsTypes/numberProgressMixin.js, src/shared/components/ncTable/mixins/columnsTypes/numberStarsMixin.js, src/shared/components/ncTable/mixins/columnsTypes/selectionMixin.js, src/shared/components/ncTable/mixins/columnsTypes/selectionMultiMixin.js, src/shared/components/ncTable/mixins/columnsTypes/textLineMixin.js, src/shared/components/ncTable/mixins/columnsTypes/textLinkMixin.js, src/shared/components/ncTable/mixins/columnsTypes/textLongMixin.js, src/shared/components/ncTable/mixins/columnsTypes/textRichMixin.js, src/shared/components/ncTable/sections/CustomTable.vue
=> fix(search): enables non case sensitive search

cypress/e2e/tables-rows.cy.js, cypress/e2e/tables-search.cy.js, cypress/e2e/tables-share.cy.js, cypress/e2e/tables-table.cy.js, cypress/e2e/tables.cy.js, src/modules/navigation/modals/CreateTable.vue, src/modules/sidebar/mixins/shareAPI.js, src/shared/mixins/generalHelper.js, src/shared/utils/displayError.js, src/store/data.js, src/store/store.js
=> fix: error handling for axios requests

src/shared/components/ncTable/partials/TableCellDateTime.vue
=> fix(datecell): Date now is no longer shown as invalid date

.github/workflows/cypress.yml, .github/workflows/integration.yml, .github/workflows/lint-php-cs.yml, cypress.config.js
=> chore/ci): add missing php extensions to action-scripts

src/shared/components/ncTable/mixins/columnsTypes/datetimeDateMixin.js, src/shared/components/ncTable/mixins/columnsTypes/datetimeMixin.js, src/shared/components/ncTable/mixins/columnsTypes/datetimeTimeMixin.js, src/shared/components/ncTable/mixins/columnsTypes/numberMixin.js, src/shared/components/ncTable/mixins/columnsTypes/numberProgressMixin.js, src/shared/components/ncTable/mixins/columnsTypes/selectionMixin.js, src/shared/components/ncTable/mixins/columnsTypes/selectionMultiMixin.js, src/shared/components/ncTable/mixins/columnsTypes/textLineMixin.js, src/shared/components/ncTable/mixins/columnsTypes/textLinkMixin.js, src/shared/components/ncTable/mixins/columnsTypes/textLongMixin.js, src/shared/components/ncTable/mixins/columnsTypes/textRichMixin.js, src/shared/components/ncTable/mixins/searchAndFilterMixin.js, src/shared/components/ncTable/partials/FilterLabel.vue, src/shared/components/ncTable/partials/TableHeader.vue, src/shared/components/ncTable/partials/TableHeaderColumnOptions.vue, src/shared/components/ncTable/sections/CustomTable.vue
Closes #302 
Enhancements:
- Enables filtering every column where it does make sense for it to be empty.
- After a filter is set, only other filters can be chosen that can be combined with the old filters in a meaningful way (constraint for usability)
=> feat(Filtering): Enables to filter for empty cells

cypress/e2e/tables-share.cy.js, src/modules/main/partials/ColumnTypeSelection.vue, src/modules/sidebar/partials/ShareForm.vue, src/shared/components/ncTable/partials/rowTypePartials/SelectionForm.vue, src/shared/components/ncTable/partials/rowTypePartials/SelectionMultiForm.vue
=> fix(NcMultiselect): Replaces NcMultiselects by NcSelects

src/shared/components/ncTable/partials/rowTypePartials/TextRichForm.vue
- put close button to the right
- add closing X for modal
closes #348 
new:
=> fix(design): adjust close options

src/shared/components/ncTable/partials/rowTypePartials/NumberForm.vue
- add the step size related to the numbers of decimals
- round the input value for the given span
closes #285
=> fix(numbers input): respect the number of decimals configured

img/app-dark.svg, img/app.svg
=> Revert "feat: more gentle icon"

src/modules/sidebar/sections/Sidebar.vue
=> design(sidebar): fix ordering

lib/Db/ColumnTypes/SelectionColumnQB.php, lib/Service/PermissionsService.php, src/shared/components/ncTable/mixins/filter.js
Opened the PR to not forget about this branch :)
=> fix(Permissions, Filter): Adjusts permissions for tables, removes filters for selection columns

src/modules/main/sections/Dashboard.vue, src/modules/main/sections/DataTable.vue, src/modules/main/sections/View.vue, src/modules/navigation/partials/NavigationTableItem.vue, src/modules/navigation/partials/NavigationViewItem.vue, src/modules/sidebar/sections/Sidebar.vue
Fix https://github.com/nextcloud/tables/issues/460
=> fix: Replace creation with connection icon

src/modules/main/partials/editViewPartials/sort/SortForm.vue
=> Changed grammar

appinfo/info.xml, lib/Db/ColumnTypes/SuperColumnQB.php, lib/Db/RowMapper.php
- add support for views and specially filtering
- see known bugs: https://github.com/nextcloud/tables/issues/453#issuecomment-1700465328
closes #453
=> fix(db): add sqlite support

src/shared/components/ncTable/mixins/magicFields.js
closes: #500 
CI sqlite errors are unrelated here...
=> fix(widget): fix errors on public shares that includes a tables widget

src/router.js
=> fix(links): add routes for */content urls

css/grid.css
for space between header and table-option-area
closes #457
=> fix(design): set background color

src/shared/components/ncTable/partials/TableCellNumber.vue
=> fix(number presentation): round the numbers to its column definition

lib/Command/ChangeOwnershipTable.php, lib/Service/PermissionsService.php, lib/Service/ShareService.php, lib/Service/TableService.php
=> fix(occ): change sender if a table owner changes

src/modules/navigation/partials/NavigationTableItem.vue, src/modules/navigation/partials/NavigationViewItem.vue, src/modules/navigation/sections/Navigation.vue
=> fix(design): remove share icon if listed in share-list

lib/Api/V1Api.php, lib/Controller/Api1Controller.php, lib/Controller/RowController.php, lib/Reference/ContentReferenceHelper.php, lib/Reference/ReferenceHelper.php, lib/Service/RowService.php
=> fix: make the userId configurable for the analytics data provider to use

.github/workflows/cypress.yml, cypress/e2e/tables-unified-search.cy.js, cypress/support/commands.js, cypress/support/local-setup.sh
- this allows to run the tests locally and in CI with the same setup
closes #549
=> make use of dev setup default user

lib/Service/TableService.php, src/modules/navigation/partials/NavigationTableItem.vue, src/modules/navigation/partials/NavigationViewItem.vue, src/modules/navigation/sections/Navigation.vue
- only show if hasShares and you are the owner
- don't show hasShares if shared with you
closes #548
=> fix(design): correct show share icon

src/modules/modals/EditColumn.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/DatetimeDateForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/DatetimeForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/DatetimeTimeForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/NumberForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/NumberProgressForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/NumberStarsForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/SelectionCheckForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/SelectionForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/SelectionMultiForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/TextLineForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/TextLinkForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/TextLongForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/TextRichForm.vue, src/shared/components/ncTable/partials/rowTypePartials/TextLinkForm.vue
- add configuration to avoid saving incorrect column configs
- add info cards if no providers are chosen
=> fix(design): fix loading the default column-link providers

src/shared/components/ncEditor/NcEditor.vue
=> fix(chore): handle editor if it could not be initialized

src/views/partials/SearchAndSelectOption.vue
=> fix(design): show rows count even if it's 0

src/modules/main/partials/editViewPartials/filter/FilterEntry.vue
=> fix(view): handle selection-check magic values

cypress/e2e/tables-fe-filters.cy.js, src/modules/navigation/sections/Navigation.vue, src/store/store.js
=> test(e2e): add e2e test for navigation filtering

src/modules/main/sections/MainWrapper.vue, src/shared/components/ncTable/NcTable.vue, src/shared/components/ncTable/mixins/exportTableMixin.js
=> fix: use the title directly instead of passing complete objects

.github/workflows/integration.yml, .github/workflows/lint-php.yml
=> chore(php): Add PHP 8.3 to test matrix

src/shared/components/ncTable/partials/TableHeader.vue, src/shared/components/ncTable/partials/TableHeaderColumnOptions.vue
=> fix(edit column action): remove outdated condition

cypress/e2e/tables-import.cy.js, cypress/fixtures/test-import.csv, src/main.js, src/modules/modals/Import.vue, src/shared/components/ncTable/partials/rowTypePartials/RowFormWrapper.vue
=> Add end2end import test

src/shared/components/ncTable/mixins/exportTableMixin.js
=> fix(export): add meta column values to export csv

lib/Controller/RowController.php, lib/Db/ColumnMapper.php, lib/Service/ColumnTypes/SelectionCheckBusiness.php, lib/Service/ImportService.php, lib/Service/RowService.php, lib/Service/TableTemplateService.php, src/shared/components/ncTable/partials/TableRow.vue, tests/integration/features/api/tablesapi.feature
- add parsing
- code cleanup
- adjust tests
closes #618
=> fix(data types): parse data for the regarding column type on insert or update

cypress/e2e/tables-export-csv.cy.js, cypress/plugins/index.js, cypress/support/commands.js, package-lock.json, package.json
=> test(export): add simple csv export test (end2end)

appinfo/info.xml
=> chore(bump): bump supported versions up to NC28

lib/Service/ColumnTypes/TextLinkBusiness.php
this fix should bring back a green CI...
=> fix(column link): fix parsing json instead using regex

lib/Service/ColumnTypes/TextLinkBusiness.php
Signed-off-by: Florian Steffens <florian.steffens@nextcloud.com>
(cherry picked from commit 60c8ba75dc908d9aeeb78b4c020b3a71cb966f43)
=> fix(column link): fix parsing json instead using regex (#654)

cypress/e2e/tables-export-csv.cy.js
-> to meet the file names correctly
=> fix(test): expand hours and minutes if they are just 1 character long

cypress/e2e/column-number-progress.cy.js, cypress/e2e/column-number-stars.cy.js, cypress/e2e/column-number.cy.js, cypress/e2e/column-selection-check.cy.js, cypress/e2e/column-selection-multi.cy.js, cypress/e2e/column-selection.cy.js, cypress/e2e/column-text-line.cy.js, cypress/e2e/tables-fe-filters.cy.js, cypress/e2e/tables-unified-search.cy.js, cypress/support/commands.js, lib/Service/ColumnTypes/DatetimeBusiness.php, lib/Service/ColumnTypes/DatetimeDateBusiness.php, lib/Service/ColumnTypes/DatetimeTimeBusiness.php, lib/Service/ColumnTypes/IColumnTypeBusiness.php, lib/Service/ColumnTypes/NumberBusiness.php, lib/Service/ColumnTypes/NumberProgressBusiness.php, lib/Service/ColumnTypes/NumberStarsBusiness.php, lib/Service/ColumnTypes/SelectionBusiness.php, lib/Service/ColumnTypes/SelectionCheckBusiness.php, lib/Service/ColumnTypes/SelectionMultiBusiness.php, lib/Service/ColumnTypes/SuperBusiness.php, lib/Service/ColumnTypes/TextLinkBusiness.php, lib/Service/RowService.php, src/modules/modals/CreateColumn.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/SelectionForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/SelectionMultiForm.vue, src/shared/components/ncTable/partials/columnTypePartials/forms/TextLineForm.vue, src/shared/components/ncTable/partials/rowTypePartials/NumberForm.vue
- allow empty values and parse them correctly
- handle selection ids and labels to match to the defined options
- cleanup
closes #663 
closes #672 
closes #674 
closes #667
=> fix(column value parsing): fix parsing all values for each related column type

src/shared/components/ncTable/partials/rowTypePartials/RowFormWrapper.vue
=> fix(description text): pre line breaks

cypress/e2e/column-datetime.cy.js, cypress/e2e/column-datetimeDate.cy.js, cypress/e2e/column-datetimeTime.cy.js, cypress/support/commands.js, lib/Service/ColumnTypes/DatetimeBusiness.php
=> fix(datetime): fix handling empty datetime values and add tests #676

src/modules/sidebar/sections/SidebarIntegration.vue
=> fix(sidebar): fix copy to clipboard on error message

src/shared/components/ncTable/mixins/columnsTypes/numberStars.js, src/shared/components/ncTable/mixins/filter.js
- handle NaN for parseInt
- change sorting logic
- disable filter operator "is empty" as this is not needed here
closes #325
=> fix(filter): correct handling of empty values for column stars

cypress/e2e/column-datetime.cy.js, cypress/e2e/column-datetimeTime.cy.js
=> fix(test): use virtual clock instead of using the real time

src/shared/components/ncTable/partials/columnTypePartials/forms/MainForm.vue
=> fix(design): only show views selection if there are any views

lib/Controller/AOCSController.php
=> fix(i18n): Fixed grammar

lib/Db/Column.php, lib/Service/ColumnService.php, src/modules/main/partials/ColumnInfoPopover.vue, src/modules/modals/EditColumn.vue, src/shared/components/ncTable/mixins/columnClass.js
=> [stable0.6] fix: add display names to all column meta data printouts

CHANGELOG.md, appinfo/info.xml, package.json
Prepared pull request to bump version and add changelog for walking through the release process with @enjeck
=> chore: Bump version to 0.6.6

.github/ISSUE_TEMPLATE/bug-report.yml
left 7.4 as the current version supports it.
=> Update PHP options in issue template

lib/Migration/Version000800Date20240213123743.php
accidentally set the wrong type there.
=> fix(DB): type of context_id must be int

cypress/e2e/tables-archive.cy.js, cypress/e2e/tables-favorite.cy.js
Added Cypress testing for the features added in #893
=> cypress testing for archive/favorite

CHANGELOG.md, appinfo/info.xml, package.json
Towards releasing Tables 0.7.0-beta.3
=> chore: bump to version 0.7.0-beta.3

src/shared/components/ncTable/sections/CustomTable.vue
=> feat: add vertical column lines to Tables

src/modules/modals/CreateContext.vue, src/modules/modals/EditContext.vue, src/pages/Context.vue
Addressing design review tasks https://github.com/nextcloud/tables/issues/935
=> enh: some design review tasks

lib/Service/TableTemplateService.php
Fixes #948 
Attempt to fix the vacation template by not using negative indices
=> fix: Vacation Request template

appinfo/info.xml, renovate.json
I branched off a stable0.7 branch so we can target 0.8 on main
=> chore: Bump version to 0.8.0-dev.1

CHANGELOG.md, appinfo/info.xml, package.json
Signed-off-by: Julius Härtl <jus@bitgrid.net>
=> chore(release): Bump version to 0.7.1

lib/Db/ContextNodeRelationMapper.php, lib/Db/PageContentMapper.php, lib/Db/PageMapper.php, lib/Service/ContextService.php, lib/Service/ShareService.php, src/modules/modals/CreateContext.vue, src/modules/modals/DeleteContext.vue, src/modules/modals/EditContext.vue, src/modules/modals/Modals.vue, src/modules/navigation/partials/NavigationContextItem.vue, src/shared/components/ncTable/mixins/permissionsMixin.js, src/store/store.js
=> enh: Delete Application and its shares

src/modules/modals/CreateContext.vue, src/modules/modals/CreateTable.vue, src/modules/modals/EditContext.vue, src/modules/modals/EditTable.vue, src/modules/modals/ViewSettings.vue
Simple grammar fix for table title character limit across the code. (l10 improvement)
=> fix(l10n): grammar fixes for table char limits

lib/Controller/ImportController.php, src/modules/modals/Import.vue
=> feat: update error handling during import

src/App.vue, src/modules/modals/CreateTable.vue, src/store/store.js
=> fix: reduce templates requests

src/modules/modals/CreateRow.vue, src/modules/modals/EditRow.vue
=> feat: submit row details with ctrl + enter

src/shared/components/ncTable/mixins/columnClass.js, src/shared/components/ncTable/mixins/columnsTypes/datetime.js, src/shared/components/ncTable/mixins/columnsTypes/datetimeDate.js, src/shared/components/ncTable/mixins/columnsTypes/datetimeTime.js, src/shared/components/ncTable/mixins/columnsTypes/number.js, src/shared/components/ncTable/mixins/columnsTypes/numberProgress.js, src/shared/components/ncTable/mixins/columnsTypes/numberStars.js, src/shared/components/ncTable/mixins/columnsTypes/selection.js, src/shared/components/ncTable/mixins/columnsTypes/selectionCheck.js, src/shared/components/ncTable/mixins/columnsTypes/textLine.js, src/shared/components/ncTable/mixins/columnsTypes/textLink.js, src/shared/components/ncTable/mixins/metaColumns.js, src/shared/components/ncTable/sections/CustomTable.vue
=> fix: broken sort by date

tests/integration/features/APIv2.feature, tests/integration/features/bootstrap/FeatureContext.php
=> test(integration): cases against context transfer ownership

openapi.json, src/types/openapi/openapi.ts, vendor-bin/openapi-extractor/composer.lock
Latest version with some fixes.
=> chore(deps): Update openapi-extractor

tests/integration/features/APIv2.feature
contributes to #1006, filling gaps on shared contexts
=> ci(integration): add more share-related tests

lib/Controller/ContextController.php, lib/Service/ContextService.php, openapi.json, src/shared/components/ncContextResource/ResourceForm.vue, src/types/openapi/openapi.ts, tests/integration/features/APIv2.feature
=> fix: only add resource if user can manage resource

cypress/e2e/context.cy.js, cypress/support/commands.js, lib/Controller/ContextController.php, src/modules/modals/CreateContext.vue, src/modules/modals/DeleteContext.vue, src/modules/modals/EditContext.vue, src/modules/modals/TransferContext.vue, src/modules/navigation/partials/NavigationContextItem.vue, src/modules/navigation/sections/Navigation.vue, src/shared/components/ncContextResource/NcContextResource.vue, src/shared/components/ncContextResource/ResourceSharePermissions.vue, src/shared/components/ncTable/NcTable.vue
- Create an application with a resource
- Edit the application and remove the resource with the "delete" button
- Save
- The resource is not deleted, and still shows in the application
I believe this change fixes the problem
=> fix: modify context nodes update

lib/Controller/Api1Controller.php, lib/Controller/RowOCSController.php, openapi.json, src/types/openapi/openapi.ts
Fixes https://github.com/nextcloud/tables/pull/1169
=> fix(api): Fix wrong array type

src/modules/modals/ViewSettings.vue
=> fix: remove View filter with null column

lib/Controller/Api1Controller.php, openapi.json, src/types/openapi/openapi.ts
Manual backport of https://github.com/nextcloud/tables/pull/1205
=> [stable0.7] fix(api): Fix wrong array type

package.json, src/types/openapi/openapi.ts
fixes the silent error when generating the openapi assets as described here: https://github.com/nextcloud/tables/pull/1215#issuecomment-2236178507
0.7 is not affected, this happened after upgrading a dev dep here on main
=> build(openapi): fix ms typescript generation command

src/modules/main/sections/ElementTitle.vue, src/shared/components/ncTable/NcTable.vue, src/shared/components/ncTable/sections/CustomTable.vue
Fixes https://github.com/nextcloud/tables/issues/1212
|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![Screenshot from 2024-07-19 11-24-09](https://github.com/user-attachments/assets/c4df8821-d941-4b7c-b886-165018d71918) | ![Screenshot from 2024-07-19 12-21-27](https://github.com/user-attachments/assets/36d9431e-181f-4e3d-90b7-4f3b08265ab5) |-------------|---------------------------------------------------------------|
| ![Screenshot from 2024-07-19 11-18-16](https://github.com/user-attachments/assets/7405a912-931a-49d1-944e-00e3adca9204)
=> fix(files): fix width, background of table row and interval between table header

src/modules/modals/EditRow.vue
Fixes https://github.com/nextcloud/tables/issues/1226
Before | After
---|---
=> Align button to the left side

src/shared/components/ncTable/sections/CustomTable.vue
Fixes https://github.com/nextcloud/tables/issues/1232
Before | After
---|---
=> fix(files): remove unneeded extra place for the rows

appinfo/info.xml
Making developing against NC master fun again =)
=> build(NC): bump max compatible NC version

cypress/styleguide/assets/default.css, src/App.vue, src/modules/navigation/partials/NavigationTableItem.vue, src/shared/components/ncTable/partials/TableHeaderColumnOptions.vue
Fixes some styling issues
|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![Screenshot from 2024-08-21 19-40-19](https://github.com/user-attachments/assets/f836e137-9c2d-4f85-84ac-706f011af9c8)| ![Screenshot from 2024-08-21 19-40-35](https://github.com/user-attachments/assets/8c3fbf4b-515a-4dae-b4e8-9e7219bb5354)|
| ![Screenshot from 2024-08-21 19-41-17](https://github.com/user-attachments/assets/564dd268-e4ea-4f23-9ba9-dfb922bdd591)| ![Screenshot from 2024-08-21 19-54-52](https://github.com/user-attachments/assets/e1f2400a-5e18-4d7c-bc48-dce7d4462cb7)|
|![image](https://github.com/user-attachments/assets/ade31489-0691-4ae6-b54a-dde33d28ffdb)|![image](https://github.com/user-attac …
=> fix: improve style alignment and heights

tests/integration/run.sh
then it can be specified in a docker-composer.yml file for instance
=> ci(behat): allow to specify scenario via env var

.github/workflows/npm-audit-fix.yml
@blizzz I think we rather want it this way
=> ci: Update npm-audit-fix.yml to match tables app branches

src/modules/modals/EditContext.vue, src/shared/components/ncContextResource/NcContextResource.vue, src/shared/components/ncContextResource/ResourceSharees.vue
=> feat: share Application with groups

composer.lock
latest phpunit has some commits regarding PHP 8.4, let's see whether tests will pass.
=> build(dev-deps): update phpunit for PHP 8.4 compat

composer.lock
Like #1466 
Should turn the tests against server master green again.
=> [stable0.8] build(dev-deps): update phpunit for PHP 8.4 compat

package-lock.json, package.json
Reverts https://github.com/nextcloud/tables/pull/1484
=> fix: revert vuecore version that dropped vue2 support

.github/workflows/cypress-custom.yml, .github/workflows/integration.yml, .github/workflows/psalm-matrix-custom.yml, .github/workflows/update-nextcloud-ocp-matrix.yml, appinfo/info.xml, cypress/e2e/tables-import.cy.js, cypress/support/commands.js
=> deps: drop support for NC 27 and 28

.github/workflows/cypress-custom.yml
Signed-off-by: Julius Knorr <jus@bitgrid.net>
=> ci: Run cypress on all runners

lib/Service/TableTemplateService.php
=> chore(i18n): Improved grammar

src/modules/modals/CreateRow.vue, src/modules/modals/ImportScheme.vue
=> fix: improve import scheme and row dialogs

package-lock.json
This audit fix resolves 11 of the total 19 vulnerabilities found in your project.
* [@nextcloud/dialogs](#user-content-\@nextcloud\/dialogs)
* [@nextcloud/l10n](#user-content-\@nextcloud\/l10n)
* [@nextcloud/moment](#user-content-\@nextcloud\/moment)
* [@nextcloud/webpack-vue-config](#user-content-\@nextcloud\/webpack-vue-config)
* [@vue/component-compiler-utils](#user-content-\@vue\/component-compiler-utils)
* [node-gettext](#user-content-node-gettext)
* [postcss](#user-content-postcss)
* [vue-loader](#user-content-vue-loader)
* [vue-resize](#user-content-vue-resize)
* [vue-template-compiler](#user-content-vue-template-compiler)
* [vuex](#user-content-vuex)
* Caused by vulnerable dependency:
* [@nextcloud/vue](#user-content-\@nextcloud\/vue)
* [vue](#user-content-vue)
* …
=> [stable0.8] Fix npm audit

lib/Db/Row2Mapper.php
Steps to reproduce:
- Create a table with a view
- Sort the view by updated at or updated by
- See an error being thrown in the logs
```
{
"reqId": "ilntC7gHiXBR7XaF2uP5",
"level": 3,
"time": "2025-03-13T05:48:00+00:00",
"remoteAddr": "2a02:8071:64e0:7bc0:2f86:72c1:6a64:1cb5",
"user": "christine",
"app": "tables",
"method": "GET",
"url": "/apps/tables/row/view/32",
"message": "An internal error or exception occurred: OCA\\Tables\\Db\\Row2Mapper - getRows: An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column sleeves.updated_at does not exist\nLINE 1: ...2, $3, $4, $5, $6, $7, $8, $9, $10, $11) ORDER BY \"sleeves\"....\n                                                             ^\nHINT:  Perhaps you meant to reference the column …
```
=> fix: use proper meta column names for sorting

lib/Db/Row2Mapper.php
Optimised the tables/views view. The main optimisation is that for each cell we no longer get the CellMapper service. I also made a couple of minor improvements.
On my machine, for a table (4000 rows and 6 columns), I got the following results when opening the page.
Before: 45 seconds
After: 5 seconds
=> refactor: optimized parseEntities for better efficiency

cypress/e2e/tables-table.cy.js, cypress/support/commands.js, src/modules/modals/EditTable.vue
- comments out lines that makes test flaky
- makes the delete test independent so that it doesn't fail due to previous tes
- improve selectors
=> fix: update table edit functionality and improve element selectors

lib/Service/ImportService.php
=> [stable0.7] style: format constructor params import methods and classes

lib/Db/Row2Mapper.php, lib/Helper/ColumnsHelper.php
This is a continuation of #1720
1. Create column of type "Users and groups"
2. Create a view with filtered column, use "me" for filter value and "contains" operator type
<details><summary>:mag: Preview</summary>
<p>
</p>
</details>
4. Add few rows with various users, groups and teams
<details><summary>:mag: Preview</summary>
<p>
</p>
</details>
5. Share view to another user
6. Open view by another user
Expected result: user is able to see rows which met to criteria
Actual result: this filter works properly only for users and not works for groups and teams
<details><summary>:mag: Preview with fix</summary>
<p>
</p>
</details>
=> Enhancement: Improve filtering by groups and teams

cypress/e2e/view-filtering-selection.cy.js
Added a test for the feature that removes rows from a view when they no longer match the filter. The test covers the following steps:
- create a view with filter for checked == true
- insert a "checked row", check server response for present to be true and DOM for be.visible
- insert a "unchecked row", check server response for present to be false and DOM for not.exists
- edit the "checked row", uncheck it, check server response for present to be false and DOM for not.exists
- inline edit "first row" (from the setup table), uncheck it, check response for present to be false and DOM for not.exists
=> test: added a test for remove filtered rows feature
