.github/workflows/node.yml

This will make sure that we have a step that builds the javascript so we can be sure that this continues to work

ci: Add node build to GitHub actions

---

src/App.vue

This fixes a few issues with the container layout on Nextcloud 25, e.g. on smaller window height

fix: Use NcContent component instead of div

---

lib/AppInfo/Application.php
lib/Datasource/AnalyticsDatasource.php
lib/Listener/AnalyticsDatasourceListener.php

Analytics accesses data via data sources.
This pull adds the data source logic to Tables.
Within Analytics, the data source "Tables App" can be selected. Additionally, the required columns can be restricted.
The following restrictions apply:
- when persisting data within the Analytics app (automation -> data load), only 3 columns can loaded and the last one has to be a key figure. This might change in the future
- when using realtime reporting, no column restrictions apply
- for most use cases, realtime reporting should be used to avoid double data storage
- for high-volume reporting, Analytics datasets should be used to store the data for high performance reporting and filtering
> ![Bildschirm­foto 2023-02-05 um 20 05 42](https://user-images.githubusercontent.com/13385119/216839531-c550bc …

Data source for the Analytics app

---

appinfo/info.xml

- the tables app make use of special json operations within the db
- the db recommendations by nextcloud server make sure the db backends support json
- sqlite is not supported
related to #211

chore(deps): limit the db backends to pgsql and mysql (mariadb)

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

After having reported some issues to this repo I stumbled upon the [list of required information for bugs reports](https://github.com/nextcloud/tables/wiki/Contribute#find-bugs). So I thought it would help others to have a form in place which asks for the relevant information.
When creating the issue forms I took a look at the issue forms in the [Mail app](https://github.com/nextcloud/mail/tree/main/.github/ISSUE_TEMPLATE) and [Contacts app](https://github.com/nextcloud/contacts/tree/main/.github/ISSUE_TEMPLATE).
---
With issue forms contributors tend to provide more detailed information which makes it easier for others to triage the issues.

chore: add issue forms

---

src/shared/components/ncTable/mixins/exportTableMixin.js

This was already removed in main, but it's part of other commits.
That's why we need this PR specially for stable0.4 branch and no backport/cherrypick.

bugfix: #237 debug message broke because of a missing condition case

---

src/modules/main/modals/CreateRow.vue
src/shared/components/ncTable/partials/TiptapMenuBar.vue
src/shared/components/ncTable/partials/rowTypePartials/TextLongForm.vue

- add a watcher to load the value
- make get method more precise if value is '' or false or 0
- reset "add more" state after closing modal
@juliushaertl This fix should be backported to stable0.4, whats the best way to do this?

bugfix: #236 load default value for text-long on create row with "add more" mode

---

src/shared/components/ncTable/partials/TableCellHtml.vue

bugfix: #207 fix css to display checkbox labels inline

---

lib/Service/TableTemplateService.php

I think the words "through" and "throw" were confused here.

correct linguistic mistake (through and throw)

---

src/modules/main/modals/CreateColumn.vue

closes #299 
- nc25 does not provide the editor API used for text-rich columns, so we provide here the simple text as default for text columns

fix(nc25 and text-editor): bring back column-type text-long for nc25

---

cypress/e2e/tables.cy.js

use a random user instead of admin

cypress: use random user instead of admin

---

src/shared/components/ncTable/NcTable.vue

Call "tables" resource (Transifex) instead of "table".

Fix : Translation of table row creation button's label

---

src/modules/main/sections/EmptyTable.vue

Call "tables" resource (Transifex) instead of "table" in order to fix :

Fix : Translation of table column creation button's label

---

src/pages/Startpage.vue

Call "tables" resource (Transifex) instead of "table" in order to fix :

Fix : Translation call on start page

---

src/shared/components/ncTable/partials/SearchForm.vue
src/shared/components/ncTable/sections/Options.vue
src/shared/mixins/viewportHelper.js

Closes #289 
When selecting a row in tables, the button can be cut with a specific screen width. This is solved by this fix.
The design should be reviewed. See #289

fix(Options): prevents buttons to get cut off

---

src/shared/components/ncEditor/NcEditor.vue

Closes #292 
Changes the z-index of the rich editor menubar to render dropdown in front of the menubar
Before:
After:
The high z-index of the rich editor menubar is an artefact from a previous version in text and can now be changed in text as well. Therefore, the patch of the text app is available in tables, this change can be reverted.

fix(EditorMenubar): Renders Rich Editor Menubar behind dropdowns

---

src/shared/components/ncTable/partials/TableCellEditor.vue

Closes #308 
Before: 
After:
Removes the unecessary padding in the rich text cell.

fix(RichTextCell): Removed unnecessary padding

---

src/shared/components/ncTable/mixins/columnsTypes/selectionCheckMixin.js
src/shared/components/ncTable/sections/CustomTable.vue

closes #300 
you can now filter for values that does not exists. Example: filter for selection-check column type (radio button, yes/no)
| Starting point |
| --- |
| <img width="426" alt="SCR-20230608-ksef" src="https://github.com/nextcloud/tables/assets/55329475/7f444162-185e-4fe7-a42c-94b7055d1024"> |
| before | after |
| --- | --- |
| <img width="455" alt="SCR-20230608-kshr" src="https://github.com/nextcloud/tables/assets/55329475/69de7326-7702-4106-9e80-0288a52f07d9"> | <img width="455" alt="SCR-20230608-ksqc" src="https://github.com/nextcloud/tables/assets/55329475/7e57322c-b84e-422d-8083-fff32bbcb731"> |

fix(table filtering): filter also for empty cell values

---

appinfo/info.xml
lib/Command/Clean.php
lib/Db/Row.php
lib/Db/RowMapper.php
lib/Service/ColumnService.php

- add occ command to clean up data sets from rows at db level
closes #200 
It might happen (route cause analysis runs in parallel) that the rows hold data from columns that are already deleted.
With this command is it possible to clean up the rows data. Use `occ tables:clean -d` for a dry run and `occ tables:clean -e` to print out only the errors.
- delete the column from `oc_tables_columns` with the id 1 (or whatever).

enh(commands): occ cleanup row data sets

---

img/app-dark.svg
img/app.svg

I find the current icon a bit out of our icon style.
Using material design icon, I suggest we use this :)
| Before | After |
|:---------:|:------:|
|![2023-08-08_15-36](https://github.com/nextcloud/tables/assets/14975046/43571493-3808-41f6-be00-df6c501a51a8)|![2023-08-08_15-36_1](https://github.com/nextcloud/tables/assets/14975046/989f8494-35de-4d3d-a6ba-0f3c045f87b1)|
Quick PR, feel free to discard :wink:

feat: more gentle icon

---

cypress/e2e/tables-share.cy.js
src/modules/sidebar/mixins/shareAPI.js

As requested by @jancborchardt 
The checkbox indicating the value is enough and we should only show a toast in an error case.
Fix https://github.com/nextcloud/tables/issues/468

fix: No need to show toast messages on success

---

lib/Controller/Api1Controller.php

Made constructor parameter $userId of type `?string` (= be optional)
If no userId is passed (aka. is null),
$this->userId is set to an empty string to not cause any problems or errors.
See #465 for more info

Avoid error on CORS requests

---

src/shared/components/ncEditor/NcEditor.vue

Fix https://github.com/nextcloud/tables/issues/499
Otherwise the editor will be initialized with an empty string and would overwrite the local value due to an initial onUpdate call

fix: Make sure to have a local value before initializing the editor

---

src/shared/components/NcTile/NcTile.vue

Follow up fix to close #248 
Tab navigation was possible but selecting a template using enter not

fix: Select tile on enter

---

renovate.json

As we are not using vue 3 for now, we can ignore this major

chore(dependencies): Exclude vue-router 4.x

---

src/modules/main/partials/ColumnInfoPopover.vue
src/modules/modals/EditColumn.vue
src/shared/components/ncTable/partials/columnTypePartials/forms/TextLineForm.vue

- add column info popover
- don't show -1 as maxTextLength, which just means unlimited
- visual fixes

fix(design): edit columns

---

.github/workflows/cypress.yml
lib/Service/TableTemplateService.php

fix(tutorial): use the new column type text-rich instead of text-long

---

.github/workflows/cypress.yml
appinfo/info.xml
cypress/e2e/tables-unified-search.cy.js
cypress/support/commands.js
img/view-dark.svg
img/view.svg
lib/Db/TableMapper.php
lib/Db/ViewMapper.php
lib/Helper/UserHelper.php
lib/Search/SearchTablesProvider.php
lib/Service/PermissionsService.php
lib/Service/TableService.php

closes #529 
closes #528 
searching for tables was missing 🙄

Fix/529 Search for tables and views

---

src/shared/components/ncTable/mixins/columnsTypes/selection.js
src/shared/components/ncTable/partials/TableHeaderColumnOptions.vue

- remove emojis to sort by the real value
- correct handling of selection-id = 0
- code cleanup
closes #462

fix(FE selection sorting): fix emoji and selection id = 0 handling

---

src/shared/components/ncTable/sections/CustomTable.vue

- this is needed because in widgets we don't have the edit-option as last column
closes #542

fix(design): don't hide last column in ncTable used in widgets

---

src/shared/components/ncTable/mixins/columnsTypes/selection.js

- seems that in some older version we stored the ids as strings
closes #553 
Assuming we have some values as strings
Before
After

fix(FE): parse values to ensure we have integer values

---

src/shared/components/ncTable/mixins/permissionsMixin.js

- wrong identifier to ask for permissions
closes #557

fix(design): show edit column actions if shared as table manager

---

APIv1.yaml

- Added the missing properties from #629.
- Specified nullability for some properties based on the `jsonSerialize` method in the DB models and `create`/`update` functions from the associated service.
- Added regex patterns to `createdAt` & `lastEditAt` of `Table`, `Share`, `Column`, `View`, `Row` components.
- Added required properties `id` & `tableId` to `Row` component.
- Added descriptions to `subtype`, `orderWeight`, `numberPrefix`, `numberSuffix`.

Improve API spec

---

src/modules/main/partials/ColumnFormComponent.vue
src/modules/main/partials/editViewPartials/filter/FilterEntry.vue
src/modules/modals/CreateColumn.vue
src/modules/modals/EditColumn.vue
src/modules/modals/Import.vue
src/shared/components/ncTable/partials/columnTypePartials/forms/TextLinkForm.vue

- use grid layout
- split fields into 2 lines
- add background and spaces to separate different filters by design
closes #611 
| Before | After |
| --- | --- |
| <img width="576" alt="SCR-20231102-jcsx" src="https://github.com/nextcloud/tables/assets/55329475/518ff670-c93b-49d2-b62e-e32656788051"> | <img width="575" alt="SCR-20231102-izzo" src="https://github.com/nextcloud/tables/assets/55329475/fdd8a194-500d-4818-9626-57fba2a63807"> |

refactor(design): redesign the filter form 

---

src/App.vue

Make sure to update the browser window title with the current table or view title.
Code is a shamless copy from deck ;)

fix: Update browser page title depending on current view/table

---

cypress/e2e/tables-rows.cy.js
src/modules/modals/CreateRow.vue
src/modules/modals/EditRow.vue

Addresses https://github.com/nextcloud/tables/issues/702

feat: add error hints for mandatory fields

---

src/views/partials/SearchAndSelectOption.vue
src/views/sections/Search.vue

Addresses: https://github.com/nextcloud/tables/issues/751

fix: increase smartpicker select height

---

lib/Service/ColumnTypes/TextLinkBusiness.php
src/shared/components/ncTable/partials/rowTypePartials/TextLinkForm.vue
tests/unit/Service/ColumnTypes/TextLinkBusinessTest.php

Fix #777 
- fix(link): Properly sanizite and map database values to what we expect it to be
- fix: Avoid failing on empty strings for URL values

Avoid failures with link column database values from previous versions

---

lib/Service/ColumnService.php
lib/Service/ColumnTypes/NumberBusiness.php
src/modules/modals/EditColumn.vue
src/shared/components/ncTable/mixins/columnClass.js
src/shared/components/ncTable/mixins/columnsTypes/number.js
src/shared/components/ncTable/mixins/columnsTypes/numberProgress.js
src/shared/components/ncTable/mixins/columnsTypes/selection.js
src/shared/components/ncTable/partials/TableCellNumber.vue
src/shared/components/ncTable/partials/TableRow.vue
src/shared/components/ncTable/partials/columnTypePartials/forms/NumberForm.vue
src/shared/components/ncTable/partials/rowTypePartials/NumberForm.vue

[stable0.6] Fix number column issues

---

cypress/e2e/view-filtering-selection.cy.js
cypress/support/commands.js
lib/Db/Row2Mapper.php
src/modules/modals/CreateRow.vue
src/shared/components/ncTable/mixins/filter.js

With the new db structure it is much easier to filter for selection values inside of multi selection columns. This should make this possible to filter for `contains` and `equal`.  
Not for `empty` for now. Needs to look into the `empty` filter in general...
related to: https://github.com/nextcloud/tables/issues/648

enh: add filtering in views for multi selection

---

cypress/e2e/view.cy.js
lib/Service/RowService.php

As seen in our call ;)
Steps to reproduce:
- Create a view with some filter
- Try to add a new row
<details>
<summary>Error traces:</summary>
```
{"reqId":"n44vxSJOKGrhjaAQmRnk","level":3,"time":"2024-01-30T09:41:00+00:00","remoteAddr":"192.168.65.1","user":"alice","app":"index","method":"POST","url":"/index.php/apps/tables/row","message":"OCA\\Tables\\Db\\Row2::setTableId(): Argument #1 ($tableId) must be of type int, null given, called in /var/www/html/apps-shared/tables/lib/Service/RowService.php on line 199 in file '/var/www/html/apps-shared/tables/lib/Db/Row2.php' line 33","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"29.0.0.4","exception":{"Exception":"Exception","Message":"OCA\\Tables\\Db\\Row2::setTableId(): Argument …
```

fix: Properly insert rows into views for the new db structure

---

CHANGELOG.md
appinfo/info.xml
package.json

chore: bump version to 0.7.0-beta.1

---

lib/Db/Row2Mapper.php
lib/Service/RowService.php

Fixes https://github.com/nextcloud/tables/issues/827
Fix for an internal finding
To reproduce:
- Create a table with a single select and some other fields
- Create a view to filter for the single select but don't include it in the visible columns list
- Load the view
Would be good to cover this case with a test, but pushed to have CI running already to be able to apply a patch as a quick fix

fix: Pass all table columns along as we need them for filtering the rows

---

cypress/e2e/view.cy.js
lib/Service/RowService.php
src/modules/main/partials/editViewPartials/filter/FilterEntry.vue
src/modules/main/partials/editViewPartials/filter/FilterForm.vue
src/modules/main/partials/editViewPartials/filter/FilterGroup.vue
src/modules/main/sections/DataTable.vue
src/modules/modals/EditRow.vue
src/modules/modals/ViewSettings.vue
src/modules/navigation/partials/NavigationViewItem.vue
src/shared/components/ncTable/partials/TableRow.vue
src/shared/components/ncTable/sections/CustomTable.vue
src/shared/components/ncTable/sections/Options.vue

This PR fixes an issue with deleting rows in a view. 
- Create a view with some rows
- Try to delete any row in the view
<details>
<summary>Error traces:</summary>
```
master-nextcloud-1  | {"reqId":"Tc9DQHagtkcXkVMZz29Q","level":3,"time":"2024-02-07T11:07:32+00:00","remoteAddr":"192.168.21.5","user":"admin","app":"tables","method":"DELETE","url":"/index.php/apps/tables/view/17/row/522","message":"Array","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"29.0.0.5","data":{"app":"tables"}}
master-nextcloud-1  | {"reqId":"Tc9DQHagtkcXkVMZz29Q","level":3,"time":"2024-02-07T11:07:32+00:00","remoteAddr":"192.168.21.5","user":"admin","app":"tables","method":"DELETE","url":"/index.php/apps/tables/view/17/row/522","message …
```

fix: properly delete rows in views

---

src/modules/modals/ViewSettings.vue

Need to use `name` instead of `title` prop, as required by nextcloud/vue v8

enh: use required name prop for NcAppSettingsSection

---

lib/Service/TableService.php

This fixes an issue with deleting Tables with have filtered Views. 
- Create a table
- Create a view with filters
- Try to delete the table
Video showing the problem:
[Screencast from 02-14-2024 12:46:02 PM.webm](https://github.com/nextcloud/tables/assets/32180937/8fbf5596-b8d2-49a5-a592-3ce4dff0deeb)
<details>
<summary>Error traces:</summary>
```
master-nextcloud-1  | {"reqId":"zp3aE2jxl2LhAy6hIRGP","level":3,"time":"2024-02-14T09:06:43+00:00","remoteAddr":"192.168.21.5","user":"admin","app":"index","method":"DELETE","url":"/index.php/apps/tables/table/1","message":"OCA\\Tables\\Db\\Row2Mapper::getFilterExpression(): Argument #2 ($column) must be of type OCA\\Tables\\Db\\Column, null given, called in /var/www/html/apps/tables/lib/Db/Row2Mapper.php on line 280 in file …
```

fix: properly delete tables with filtered view

---

package-lock.json
package.json
src/App.vue
src/modules/main/sections/Dashboard.vue
src/modules/main/sections/DataTable.vue
src/modules/main/sections/ElementDescription.vue
src/modules/navigation/sections/Navigation.vue
src/pages/Table.vue
src/pages/View.vue
src/shared/components/ncTable/NcTable.vue
src/shared/components/ncTable/sections/CustomTable.vue
src/views/ContentReferenceWidget.vue

Slightly different approach for https://github.com/nextcloud/tables/pull/342 to contribute to #631 making the table column header sticky.
Ideally we would have a combination of absolute positioning and stickyness to let the sticky container only span the outer width of the scroll container, but that seems to be impossible so I went for a resize observer that pins the width of the sticky table header and table options through a css variable which turned out to work reasonably well.
> refactor the table as css div table
> prepare for column resizing https://github.com/nextcloud/tables/issues/35
@datenangebot I don't remember exactly if the points in the old pr are still valid, but considering the refactor would still be valid, this seems like a good intermediate solution for browsing larger …

fix: Make table header sticky

---

lib/Db/Row2Mapper.php
lib/Service/TableService.php

@enjeck mentioned that even with https://github.com/nextcloud/tables/pull/842 we could still have cases where the delete failed and we are left in a kind of broken state.
This commit makes sure that we do not throw a type error but a internal one that is logged and handled gracefully and we can just skip the failing table enhancement for listing the table. This way even if a deletion failed on a previous attempt, users can still use tables, list them and delete the orphaned entry with the fix from #842

fix: Only skip failing table data loading instead of full failure

---

lib/Migration/Version000800Date20240213123743.php
psalm.xml

Implements the DB structure as proposed in #812 with these two differences:
* for consistency, I renamed "resource" to "node" how it is already named in the existing share table
* for it is not possible to have a column being nullable and part of the primary key, in navigation i changed the user_id to not be nullable and have the default set to an empty string. The intended logic therefore is changed that the default is an empty string, instead of null. Otherwise, same behaviour is envisioned.
* owner_type is now an int, to be used with constants to be introduced, as discussed
Dedicated indices will be added later on once the queries are standing. Ideally prereleases are not shipped without them being done.
:information_source: this PR is opened against a feature branch, `feat/contexts` …

feat(db): database structure for contexts

---

src/modules/main/sections/Dashboard.vue
src/modules/main/sections/ElementDescription.vue
src/modules/navigation/partials/NavigationTableItem.vue

Status icon removed from navigation sidebar as illustrated in issue #829 
Also removed from other places which I thought were not needed, such as next to the table title, the share list when sharing the table, and the views dashboard:
If these additional changes are unnecessary or should not have been changed, it can easily be rolled back to only remove the icon from the navigation sidebar as shown in the original issue.

Fix hide user status from owner avatar (issue #829)

---

src/reference.js

This change reduces the bundle size of the entry points quite heavily to make the initial page load of apps that use link preview widgets faster.
For tables this brings down the entrypoint from 4MB to 16KB
🏚️ Before | 🏡 After
---|---

perf: Optimize lazy imports for reference widgets

---

src/modules/main/sections/MainWrapper.vue
src/modules/modals/CreateColumn.vue
src/modules/modals/DeleteColumn.vue
src/modules/modals/DeleteRows.vue
src/modules/modals/EditColumn.vue
src/modules/modals/EditRow.vue
src/modules/modals/Import.vue
src/shared/components/ncTable/NcTable.vue
src/shared/components/ncTable/sections/CustomTable.vue
src/store/data.js

As part of https://github.com/nextcloud/tables/issues/807 , we want to hold multiple Tables' data in the vuex store. We do this because the data is needed for various modals to function properly

feat: hold multiple tables/views in global store

---

.github/workflows/integration.yml
lib/Db/Row2Mapper.php

Not the ideal approach probably, but should at least remove one blocker from releasing 0.7.0
Fix #849

fix: Avoid sql error on postgres

---

lib/AppInfo/Application.php
lib/Service/PermissionsService.php

The first commit is a take out from #865, the second is adding checker method.

node type constants and convenience methods to check access and manage permissions

---

appinfo/routes.php
cypress/e2e/tables-import.cy.js
lib/Controller/ImportController.php
lib/Service/ImportService.php
lib/UploadException.php
src/modules/modals/Import.vue

* Resolve: #833
* Description: Ability to import table with direct file upload.
[demo (2).webm](https://github.com/nextcloud/tables/assets/89908051/f90caa4b-ac01-43b7-8ced-0b093fdcb8ad)

feat: implement direct file upload

---

lib/Service/ColumnService.php
lib/Service/ImportService.php

* Resolve: #838 
* Description:
Autodetect data type during import.

feat: autodetect data type during import

---

lib/Db/Row2.php
lib/Service/RowService.php

When updating rows in a view I noticed a but where the second update operation of the same row wold fail in the frontend.
It turned out that the first update would actually return a column that was not in the view itself which it tried to update then on the next attempt.
This PR introduces filtering for the actual columns of a view in places where we return its data (update/delete).
Steps to reproduce:
- Create a table with some entries
- Create a view that hides one table column
- Open the view and edit a row twice

fix: Filter returned entity result by view columns

---

.github/workflows/cypress.yml
.github/workflows/integration.yml
appinfo/info.xml
lib/Service/TableTemplateService.php

for dependencies already PHP 8.x is required, contradicting NC 25 compatibility. Also, 25 is EOL.

fix(meta): drop 25 support

---

lib/Service/PermissionsService.php

Follow up to #878 – the implantation would have used the user set to the instance state, not the one provided through the argument.

fix(Permissions): check against user provided in args

---

appinfo/routes.php
composer.json
lib/Capabilities.php
lib/Command/RenameTable.php
lib/Controller/Api1Controller.php
lib/Controller/ApiFavoriteController.php
lib/Controller/ApiTablesController.php
lib/Controller/TableController.php
lib/Db/Table.php
lib/Db/View.php
lib/Migration/Version000800Date20240222000000.php
lib/ResponseDefinitions.php
lib/Service/FavoritesService.php
lib/Service/TableService.php
lib/Service/ViewService.php
src/modules/navigation/partials/NavigationTableItem.vue
src/modules/navigation/partials/NavigationViewItem.vue
src/modules/navigation/sections/Navigation.vue
src/shared/constants.js
src/store/store.js
tests/integration/features/APIv2.feature
tests/integration/features/bootstrap/FeatureContext.php

feat: Add backend for table archive and favorite flag

---

cypress/e2e/view.cy.js
src/modules/main/sections/DataTable.vue

fixes https://github.com/nextcloud/tables/issues/852

Cypress test: delete table with view

---

src/shared/components/ncTable/partials/TableCellEditor.vue
src/shared/components/ncTable/sections/CustomTable.vue
src/shared/components/ncTable/sections/Options.vue

- fix: Limit max width of text columns and properly style them
- fix: Properly center align the search/add row button
Before | After
---|---

Polish table header and text column rendering

---

lib/Db/Column.php
lib/Db/Row2Mapper.php

When gathering rows that are visible in views we need to take rows into
account that have no corresponding entry in the columns_TYPE tables. For
those we can match the filter in PHP and include row ids from a left
join where there is no entry.
Taking an example of a yes/no selection:
If the default value of a column doesn't match we end up using the same
query as before for collecting row ids
```
...
`id` IN (SELECT `row_id` FROM `oc_tables_row_cells_selection` WHERE (`column_id` = 7) AND (`value` LIKE '"false"'))
...
```
If the default value matches, we need to include those that do not have
an entry
```
...
`id` IN (SELECT `row_id` FROM `oc_tables_row_cells_selection` WHERE (`column_id` = 7) AND (`value` LIKE '"false"'))
OR
`id` IN (select sl.id from oc_tables_row_sleeves sl LEFT JOIN …
```

Match default values when querying views

---

src/modules/navigation/sections/Navigation.vue

Fix for issue #892 
Added some CSS which will further indent views which are nested in an archived table to make the hierarchy more visible. If there's a better way, definitely let me know :)
<details>
<summary>Previous</summary>
</details>
<details>
<summary>Suggested</summary>
</details>

fix: properly indent child views of archived tables

---

.github/workflows/cypress.yml
cypress/e2e/tables-import.cy.js
lib/AppInfo/Application.php
lib/Listener/LoadAdditionalListener.php
package-lock.json
package.json
src/file-actions.js
src/modules/modals/FileActionImport.vue
src/modules/modals/Import.vue
src/modules/modals/ImportResults.vue
webpack.js

This feature is in response to issue #365 
This feature adds a file action to files in the Files app, which allows you to import the file into Tables, provided it is a supported file format. Upon clicking the "Import into Tables" button in the file action menu, a dialog will be displayed which lets you choose to import the data as a new table, or if you want to import the data into an existing table.
Importing the data as a new table allows you to choose an icon and a name for the table, and if none are provided, will use the 🔧 icon and the file name for the table information. If you choose to import the file into an already existing table, it allows you to select one of your tables and gives you the choice of creating missing columns or not. *
\* Possible bug with this, will look into it …

Feat: File action to import from Files to Tables

---

appinfo/routes.php
lib/Controller/ContextController.php
lib/Service/ContextService.php
openapi.json
src/types/openapi/openapi.ts

This could also be useful btw :sweat_smile: 
contributes to #311 
Example call: `curl --silent -X DELETE -H "OCS-APIRequest: true" -u alice:password 'https://example.com/ocs/v2.php/apps/tables/api/2/contexts/12?format=json'`

API endpoint to delete a context

---

img/material/meta.json
src/modules/modals/CreateContext.vue
src/modules/modals/EditContext.vue
src/modules/navigation/partials/NavigationContextItem.vue
src/pages/Context.vue
src/shared/components/ncContextResource/ResourceList.vue
src/shared/components/ncIconPicker/NcIconPicker.vue
src/shared/components/ncIconPicker/mixins/svgHelper.js
src/shared/components/ncIconPicker/partials/Icon.vue
src/shared/components/ncIconPicker/partials/IconPicker.vue
webpack.js

Material design icon picker for Contexts.
Part of #895

feat: contexts material design icon picker

---

lib/AppInfo/Application.php
lib/Db/ContextMapper.php
lib/Listener/BeforeTemplateRenderedListener.php
lib/Service/ContextService.php

solves #863 
needs #903 (soft)
~~wants https://github.com/nextcloud/server/pull/44178~~
Screenshot made with frontend from https://github.com/nextcloud/tables/pull/844. On the content area in the UI we don't render the material icons yet, but the icon is in the nav bar. The icon over the mouse pointer is material design, while the two icons on the very right have fallback icons (default app icon).

feat(Contexts): add Contexts to navigation when applicable

---

cypress/e2e/column-selection.cy.js
src/modules/modals/CreateColumn.vue
src/modules/modals/CreateRow.vue
src/modules/modals/CreateTable.vue
src/modules/modals/ViewSettings.vue

Make sure that the modals to create new elements always focus the first input by default.

fix: Focus first input when creating  a new table/row/column/view

---

cypress/e2e/tables-favorite.cy.js
src/modules/navigation/sections/Navigation.vue

If a view is shared (the user is not the owner of the view), the user will have the option to favorite/unfavorite it, but this will not be reflected in the UI (it will not be added/removed from the favorites list).
Fix the behavior defined above. Additionally, if a table that contains views is favorited, its views will then not display a favorite/unfavorite button until the table is unfavorited. Any views which are already favorited but are also a part of the table will disappear from the favorite list as an individual view, and instead appear normally under the favorited table. This is done to prevent the view from showing in the favorites list twice.
https://github.com/nextcloud/tables/assets/23369449/02a5f820-f888-44d7-8ff9-87d1a33a0b9d

fix: shared views can be favorited

---

lib/AppInfo/Application.php

The ContentReferenceProvider was erroneously removed from Application.php, so this solution will re-add it so that content widgets will work again.

fix: reintroduce content reference provider

---

lib/Db/ContextMapper.php

I've been having an issue where, after I add a Context and try to re-fetch all Contexts from `/ocs/v2.php/apps/tables/api/2/contexts/`, the response returned by the API is a `Context[]` as expected, but the values are all `null`.
<details>
<summary>Example from before fix</summary>
```json
{
"data": [
{
"id": null,
"name": null,
"iconName": null,
"description": null,
"owner": null,
"ownerType": null,
"sharing": [],
"nodes": [],
"pages": []
}
]
}
```
</details>
This issue was preventing me from properly reviewing pull requests, so I decided to look into it. The problem was found in `ContextMapper.php`, where the row IDs were of type `string`, and the context ID variable held `int`s. They were being compared using `===` operator which, in addition to value, checks for type equivalence. …

fix(api): ContextMapper now coerces the row ID to an int for proper comparison

---

lib/Db/Context.php
lib/Db/ContextMapper.php
lib/Db/ContextNodeRelation.php
lib/Db/PageContent.php

When running on MySQL, types are returned as string, not the actual column type. We need to make sure that they have to correct type.

fix(Contexts): explicitely state non-int types

---

src/shared/components/ncTable/partials/rowTypePartials/NumberForm.vue

Fixes https://github.com/nextcloud/tables/issues/926

fix: limit min and max numbers

---

lib/AppInfo/Application.php
lib/Db/LegacyRowMapper.php
lib/Db/RowCellSuper.php
lib/Event/RowDeletedEvent.php
lib/Event/TableDeletedEvent.php
lib/Event/TableOwnershipTransferredEvent.php
lib/Event/ViewDeletedEvent.php
lib/Listener/WhenRowDeletedAuditLogListener.php
lib/Listener/WhenTableDeletedAuditLogListener.php
lib/Listener/WhenTableTransferredAuditLogListener.php
lib/Listener/WhenViewDeletedAuditLogListener.php
lib/Service/RowService.php
lib/Service/Support/AuditLogServiceInterface.php
lib/Service/Support/DefaultAuditLogService.php
lib/Service/TableService.php
lib/Service/ViewService.php
tests/unit/Listener/WhenRowDeletedAuditLogTest.php
tests/unit/Listener/WhenTableDeletedAuditLogTest.php
tests/unit/Listener/WhenTableOwnerTransferredAuditLogTest.php
tests/unit/Listener/WhenViewDeletedAuditLogTest.php
tests/unit/Service/Support/DefaultAuditLogServiceTest.php

This PR introduces audit logging for critical operations in the Tables app, addressing [issue #956](https://github.com/nextcloud/tables/issues/956). The goal is to enhance compliance measures by logging critical operations into a dedicated log file.
* Introduced `AuditLogServiceInterface`, which outlines the contract for audit logging within the application. The `DefaultAuditLogService` is the default implementation that dispatches `CriticalActionPerformedEvent` to interact with the AuditLog App. This service is auto-resolved by registering it in the Dependency Injection Container `Application.php`. This design allows for future extensibility, such as integrating different logging methods or services for AuditLog.
* Developed event dispatchers for corresponding events to trigger audit …

feat: Write critical operations to the audit log

---

appinfo/info.xml

The nextcloud server is now at version 30, so we need this update to make the app run on latest server code

enh: set nextcloud 30 as max version

---

lib/Db/ContextMapper.php
lib/Service/ContextService.php
lib/Service/PermissionsService.php
lib/Service/TableService.php
lib/Service/ViewService.php
src/modules/modals/CreateContext.vue
src/modules/modals/EditContext.vue
src/pages/Context.vue
src/shared/components/ncContextResource/NcContextResource.vue
src/shared/components/ncContextResource/ResourceForm.vue
src/shared/components/ncContextResource/ResourceSharePermissions.vue
src/shared/components/ncContextResource/ResourceSharees.vue
src/shared/components/ncContextResource/mixins/permissionBitmask.js
src/shared/constants.js
src/store/store.js
tests/integration/features/bootstrap/FeatureContext.php

Adds a way to share contexts as well as permission for associated context resources

feat: Application sharing frontend

---

appinfo/routes.php
lib/Controller/Api1Controller.php
lib/Controller/ShareController.php
lib/Db/ContextMapper.php
lib/Db/ContextNavigation.php
lib/Db/ContextNavigationMapper.php
lib/ResponseDefinitions.php
lib/Service/ContextService.php
lib/Service/PermissionsService.php
lib/Service/ShareService.php
lib/Service/TableService.php
lib/Service/ViewService.php
openapi.json
src/modules/modals/CreateContext.vue
src/modules/modals/EditContext.vue
src/pages/Context.vue
src/shared/components/ncContextResource/NcContextResource.vue
src/shared/components/ncContextResource/ResourceForm.vue
src/shared/components/ncContextResource/ResourceSharePermissions.vue
src/shared/components/ncContextResource/ResourceSharees.vue
src/shared/components/ncContextResource/mixins/permissionBitmask.js
src/shared/constants.js
src/store/store.js
src/types/openapi/openapi.ts
tests/integration/features/bootstrap/FeatureContext.php

contributes to #311 and #897
* `createShare` endpoints where extended with the optional parameter `displayMode`, which is only effective for contexts. The permissions flags on the other hand are not effective for contexts at the moment.
* `updateShareDisplayMode` (Routes: `api1#updateShareDisplayMode` and `share#updateDisplayMode`) endpoint was added, as the only updatable endpoint was against purely against permissions.
* business logic was adjusted to supply contexts specific needs.

feat(Context): add share logic for contexts

---

cypress/e2e/tables-table.cy.js
src/modules/modals/CreateTable.vue

* Resolves: #836
[demo.webm](https://github.com/nextcloud/tables/assets/89908051/9dacf4bf-88d0-457d-b280-6872af271501)

feat: create new table from import

---

src/modules/modals/CreateContext.vue

We used to set the icon on load to the promise returned by setIcon, so without changing the icon the creation failed.
Fix #1000

fix: Properly set random icon on load

---

lib/Db/Row2Mapper.php

When you have a view with a filter on last edited (cf. screenshot), loading the view would end in an "Unknown error", actually `OCA\Tables\Db\Row2Mapper - getWantedRowIds: Could not convert PHP value '2024-01-01 00:01' to type datetime. Expected one of the following types: null, DateTime, DateTimeImmutable`.

fix(filter): pass datetime object for PARAM_DATE

---

lib/Db/Column.php
lib/Db/ColumnMapper.php
lib/Db/ColumnTypes/SuperColumnQB.php
lib/Db/Row2Mapper.php
lib/Service/TableTemplateService.php
src/shared/components/ncTable/mixins/exportTableMixin.js
src/shared/components/ncTable/partials/TableRow.vue
src/shared/components/ncTable/sections/CustomTable.vue
src/shared/constants.js

- **fix: Avoid failing if a view filter contains a meta column**
- **chore: Move meta column identifiers to constants**
Likely fixes #998

Fix filters for meta columns

---

lib/Controller/ContextController.php
lib/Service/ContextService.php
openapi.json
src/types/openapi/openapi.ts
tests/integration/features/APIv2.feature
tests/integration/features/bootstrap/CollectionManager.php
tests/integration/features/bootstrap/FeatureContext.php

This PR includes some foundations for Context integration tests and a couple of create and read scenarios, plus some smaller fixes.
Let's got with this and add more scenarios in follow-ups. I'll open an overview issue.
Creation
Reading
- ensure that node parameters are treated as integer values
- report node permissions on creation
- normalization of page result format 
- atomic handling of DB inserts on create + error handling + openapi update

test(Integration): add contexts related tests

---

src/App.vue

This is sort of a PoC actually. Addresses #933 
I looked at the backend options first. The problem is that we are currently working with a set anchor, i.e. *example.com/index.php/apps/tables/**#/application/28***, so that is no information that we have on the backend. We'd either have to change this behaviour, or to avoid completely reloading the Tables app, having a mechanism that works with both, an URL that can be understood by the server, and the inside-app URL with the anchor.
Nevertheless, I looked at the frontend bits for a quick win. And there is the quick win:
[Screencast_20240430_113348.webm](https://github.com/nextcloud/tables/assets/2184312/3e1bb2b4-1108-4098-8074-e048ce5216eb)
It is not ideal though, because
- the active entry is visible flicking from Tables to the Tables …

enh(Contexts): set active navigation entry

---

lib/Db/View.php
lib/Db/ViewMapper.php

Currently we were doing n+1 queries just to get the ownership for each table.
We should also add a index for the table_id column on oc_tables_views, but tracking that in #982

perf: Avoid extra queries to get the view ownership

---

lib/Service/FavoritesService.php

We always missed the cache as we store false in the cache and that is the same as not having a value set.
This avoids running the query multiple times

perf: Make cache usable for unfavorited entries

---

appinfo/info.xml
lib/Migration/DbRowSleeveSequence.php
psalm.xml

fixes #1029 
On (at least) Postgres the migration logic from 0.6.6 to 0.7 inserts rows into oc_tables_row_sleeves with the id parameter set. It is an autoincrement column, but when the ids are specified manually, the backing sequence is not updated automatically. It then leads to constraint violation when adding new rows.
Doctrine does not offer much to interact with sequences, so here is a fall back a manual query that follows SQL standard.

fix(DB): update tables_row_sleeves' sequence after migration

---

lib/Middleware/PermissionMiddleware.php
tests/integration/features/APIv2.feature
tests/integration/features/bootstrap/FeatureContext.php

contributes to #1006
- also changes PermissionMiddleware to turn expected Exceptions into Responses for proper status codes.

ci(integration): tests against context deletion

---

appinfo/routes.php
lib/Controller/PageController.php
lib/Listener/BeforeTemplateRenderedListener.php
package-lock.json
package.json
src/App.vue
src/modules/navigation/sections/Navigation.vue

This is a more finegrained approach to to #933. The PR introduces an endpoint for each Context, so they can have the correct navigation item highlighted from the beginning, solving a known papercut from https://github.com/nextcloud/tables/pull/1037
It also sets an initial state, so that in Vue we can apply the actual route. Alas, the Vue Router adds the same information into the address bar, duplicating "app[lication]" and the context id. This is not nice. I reset it to the original URL (accepting #/), but it comes at the cost of flickering. In Vue the route cannot be applied without changing the address bar, which is a known drawback.
Another tweak: I disable the app navigation, when the Context is opened from its specific URL, making it more "standalone". Questionable if we want it. …

enh(App): navigation tweaks for Contexts

---

lib/Db/PageMapper.php

fix(DB): fetch pageId as int

---

cypress/e2e/column-datetimeDate.cy.js

Should fix the failing cypress tests ending in
```
1) Test column date
Insert and test rows - default now:
AssertionError: Timed out retrying after 10000ms: Expected to find content: 'June' within the element: <div> but never did.
at Context.eval (webpack://tables/./cypress/e2e/column-datetimeDate.cy.js:59:86)
```

test(cypress): fix month names

---

lib/Controller/ContextController.php
lib/Service/ContextService.php
openapi.json
src/types/openapi/openapi.ts
tests/integration/features/APIv2.feature
tests/integration/features/bootstrap/FeatureContext.php

contributes to #1006 ("Updating Context")
- includes a fix that ensures the data types and presence of required data in `$nodes` parameters on Controller level instead. This includes an compatible open API update ("permissions" not required anymore, defaults to READ).

ci(integration): tests against context updates

---

lib/Controller/Api1Controller.php
lib/Controller/ShareController.php
lib/Middleware/Attribute/RequirePermission.php
lib/Middleware/PermissionMiddleware.php
lib/Service/PermissionsService.php
lib/Service/ShareService.php
openapi.json
src/types/openapi/openapi.ts
tests/integration/features/APIv1.feature
tests/integration/features/bootstrap/FeatureContext.php

- also updates openapi, "context" was missing as a valid option
contributes to #1006

ci(integration): test against context sharing

---

lib/Db/View.php
lib/Service/ViewService.php

fixes #1131 
- the actual fix is in the first commit, https://github.com/nextcloud/tables/commit/c90568d11cac226ff94092f4b1ff344f872482eb
- the second one has style and minor adjustments only, just housekeeping

fix(View): 'manageTable' array key is not always set

---

.gitignore

Any screenshots or downloads from running Cypress tests are stored in the cypress/downloads folder. I don't think anything from here should be commited.

enh: gitignore Cypress download folder

---

src/modules/main/sections/EmptyTable.vue

fix: hide Create Column button on empty table if inadequate permissions

---

lib/Service/ContextService.php

There's a bug with updating context. To reproduce:
- Create a context without any tables/views
- Save context
- Edit context and add a table or view
- Try to save. There's an error. 
<details>
<summary>Error Trace</summary>
```json
"OCA\\Tables\\Controller\\ContextController",
"update",
[
"OC\\AppFramework\\DependencyInjection\\DIContainer"
],
[
"1",
"ocs.tables.context.update"
]
]
},
{
"file":"/var/www/html/ocs/v1.php",
"line":43,
"function":"match",
"class":"OC\\Route\\Router",
"type":"->",
"args":[
"/ocsapp/apps/tables/api/2/contexts/1"
]
},
{
"file":"/var/www/html/ocs/v2.php",
"line":7,
"args":[
"/var/www/html/ocs/v1.php"
],
"function":"require_once"
}
],
"File":"/var/www/html/apps/tables/lib/Db/PageContentMapper.php",
"Line":37
}, …
```

fix: insert context startpage for proper update

---

src/shared/components/ncTable/sections/CustomTable.vue

It's good for accessibility if the `NcSelect` component has an aria-label. 
Plus, this fixes the error in the console:
<details>
<summary> Console Error </summary>
vue.runtime.esm.js:4625 [Vue warn]: [NcSelect] An `inputLabel` or `ariaLabelCombobox` should be set. If an external label is used, `labelOutside` should be set to `true`.
found in
---> <NcSelect>
<CustomTable> at src/shared/components/ncTable/sections/CustomTable.vue
<NcTable> at src/shared/components/ncTable/NcTable.vue
<TableView> at src/modules/main/partials/TableView.vue
<DataTable> at src/modules/main/sections/DataTable.vue
<TableWrapper> at src/modules/main/sections/TableWrapper.vue
<Context> at src/pages/Context.vue
<NcAppContent>
<NcContent>
<App> at src/App.vue
<Root>
</details>

fix: add aria-label to NcSelect

---

src/modules/main/sections/EmptyView.vue
src/modules/main/sections/View.vue

When an empty view is in a context, sometimes, the `activeView` is null which breaks the component. It's better if we just pass in the view as a prop, just like we do for `EmptyTable`.

fix: pass view as prop to EmptyView

---

lib/Controller/Api1Controller.php
openapi.json
src/types/openapi/openapi.ts

fix(API): declared array shape was not correct

---

appinfo/routes.php
lib/Controller/RowOCSController.php
lib/Helper/ConversionHelper.php
lib/Middleware/PermissionMiddleware.php
lib/Model/Permissions.php
lib/Model/RowDataInput.php
lib/Service/PermissionsService.php
lib/Service/RowService.php
openapi.json
src/types/openapi/openapi.ts
tests/integration/features/APIv2.feature
tests/integration/features/bootstrap/FeatureContext.php
tests/integration/run.sh

solves #1105 
also features
:sparkles: completed and flexible PermissionMiddleware
:sparkles: integration tests of new endpoint against both tables and views, owners and sharees, negative tests
:sparkles: the advertised new OCS endpoint for creating rows
:sparkles: helper model to avoid a loose array with set or not set keys flying around
:sparkles: simple conversion helper to translate stringy node types to ints and other way around
Open question: should I create endpoints for all other row-related methods as well? Would make sense, this feels incomplete. Can do a follow up as well of course.

enh(API): add OCS API to create rows

---

lib/Analytics/AnalyticsDatasource.php
lib/Listener/AnalyticsDatasourceListener.php
tests/stub.phpstub

- when column type selection is used, the API needs to deliver the labels, and not the internal ids
fixes https://github.com/Rello/analytics/issues/385
- Using lib/Analytics (and not lib/Datasource) for better readability
- Adopting from LegacyRow to Row

Extract selection option labels for Analytics

---

.github/workflows/cypress-custom.yml
.github/workflows/integration.yml
.github/workflows/npm-audit-fix.yml
.github/workflows/update-nextcloud-ocp-matrix.yml
appinfo/info.xml
cypress/e2e/tables-import.cy.js
lib/Controller/RowOCSController.php
lib/Middleware/PermissionMiddleware.php

Signed-off-by: Julius Härtl <jus@bitgrid.net>

chore: Drop Nextcloud 26 for the next release as it is EOL

---

cypress/e2e/context.cy.js
cypress/support/commands.js
src/modules/modals/CreateContext.vue
src/modules/modals/DeleteContext.vue
src/modules/modals/EditContext.vue
src/modules/modals/TransferContext.vue
src/modules/navigation/partials/NavigationContextItem.vue
src/modules/navigation/sections/Navigation.vue
src/shared/components/ncContextResource/NcContextResource.vue
src/shared/components/ncContextResource/ResourceSharePermissions.vue
src/shared/components/ncTable/NcTable.vue

enh: add context e2e tests

---

lib/Db/Table.php
lib/Db/View.php
lib/Model/Permissions.php
lib/ResponseDefinitions.php
lib/Service/PermissionsService.php
lib/Service/ShareService.php
lib/Service/TableService.php
lib/Service/ViewService.php

Solves issues with undefined array keys, but is said to be more performant but also more clear when coding.
fixes #1131

fix(Backend): use object over loose array for permissions

---

cypress/e2e/context.cy.js
cypress/e2e/tables-import.cy.js
cypress/e2e/tables-rows.cy.js
cypress/e2e/tables-share.cy.js
cypress/e2e/tables-table.cy.js
cypress/support/commands.js
src/modules/modals/CreateTable.vue
src/modules/navigation/sections/Navigation.vue

The styling of some Nextcloud Vue components, which is causing some Cypress tests to fail. This fixes those failing tests, as well as uses selectors that are more robust to styling changes

fix: flaky Cypress tests

---

src/shared/components/ncTable/sections/CustomTable.vue

Fixes https://github.com/nextcloud/tables/issues/1211
- remove pagination of there is just one page
- set spread for the box shadow to 6px
- remove sticky position
Before | After
---|---

fix(files): remove pagination of there is just one page

---

lib/Service/ViewService.php

for #1173 cannot be backported, this is a low-effort and pragmatic fix for 0.7 against #1131

[stable0.7] fix(ViewService): treat missing index manageTable pragmatically

---

lib/Db/View.php

fixes #1188
TODO: in a follow up PR(s): prevent save in frontend, and repair step to clean the database from such entries.

fix(View): column might be saved as null

---

appinfo/routes.php
lib/Controller/Api1Controller.php
lib/Controller/ApiTablesController.php
lib/Controller/TableScheme.php
lib/Db/Table.php
lib/Service/TableService.php
openapi.json
src/modules/modals/CreateTable.vue
src/modules/modals/ImportScheme.vue
src/modules/modals/Modals.vue
src/modules/navigation/partials/NavigationTableItem.vue
src/types/openapi/openapi.ts

add scheme import and export

---

src/modules/modals/CreateContext.vue
src/modules/modals/CreateTable.vue
src/modules/modals/EditTable.vue

Fixes https://github.com/nextcloud/tables/issues/1214
|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![Screenshot from 2024-07-18 11-15-11](https://github.com/user-attachments/assets/b0ac0719-c2f6-48e5-974c-c84c6e5d48b4) | ![Screenshot from 2024-07-26 10-48-10](https://github.com/user-attachments/assets/a5c8b7f4-187c-42a4-834c-3704de48f725) |-------------|---------------------------------------------------------------|
| ![Screenshot from 2024-07-18 11-15-31](https://github.com/user-attachments/assets/e22bd2b8-5e57-4e56-b3a9-a32146d7fc93) | ![Screenshot from 2024-07-26 10-47-57](https://github.com/user-attachments/assets/90b9257f-e86b-4c85-85d9-7b411cf729fe) …

fix(files): align icon to center

---

src/modules/navigation/partials/NavigationTableItem.vue
src/modules/navigation/partials/NavigationViewItem.vue

fix: Navigation table entries UI issues

---

cypress/e2e/column-usergroup.cy.js
src/shared/components/ncTable/partials/TableCellUsergroup.vue
src/shared/components/ncTable/partials/rowTypePartials/UsergroupForm.vue

- Use the displayname if present
- Use NcUserBubble instead of custom styling
With user status we render it larger:

fix: Make user listing in table more consistent by using NcUserBubble

---

lib/Service/PermissionsService.php
lib/Service/ViewService.php

Fixes a couple of log findings:
https://nextcloud-gmbh.sentry.io/share/issue/541ed23a30da423b81b8ec43d52a9d8b/
https://nextcloud-gmbh.sentry.io/share/issue/e8250bd9c66e4cf89d77665744ae96d9/
https://nextcloud-gmbh.sentry.io/share/issue/855f1af7127d422d923a6bdd2ea4872f/

fix: Avoid variable access on unhandled exception and lower log level for expected permission check failures

---

src/modules/modals/CreateRow.vue
src/modules/modals/EditRow.vue
src/shared/components/ncTable/mixins/rowHelper.js

fix: ensure default values show as filled

---

.devcontainer/setup.sh
.eslintrc.js
.gitattributes
.github/workflows/app-upgrade-mysql.yml
.github/workflows/command-rebase.yml
.github/workflows/cypress-custom.yml
.github/workflows/integration.yml
.github/workflows/psalm-matrix-custom.yml
.gitignore
.l10nignore
.nextcloudignore
.php-cs-fixer.dist.php
CHANGELOG.md
LICENSES/AGPL-3.0-or-later.txt
LICENSES/Apache-2.0.txt
LICENSES/MIT.txt
Makefile
README.md
REUSE.toml
appinfo/info.xml
babel.config.js
cypress.config.js
krankerl.toml
phpunit.integration.xml
phpunit.xml
psalm.xml
tests/phpcs.xml
tests/psalm-baseline.xml
webpack.config.js

As a first step convert a larger chunk of files to ship SPDX header where our converter won't be of any help...
---
* Bad licenses: 0
* Deprecated licenses: 0
* Licenses without file extension: 0
* Missing licenses: 0
* Unused licenses: 0
* Used licenses: Apache-2.0, AGPL-3.0-or-later, MIT
* Read errors: 0
* Files with copyright information: 604 / 1179
* Files with license information: 580 / 1179

Add reuse compliance - Part 1

---

lib/Controller/AOCSController.php
lib/Controller/Api1Controller.php
lib/Controller/ApiGeneralController.php
lib/Controller/Errors.php

While testing a PR i noticed error logging is quite odd with just the message being logged without an exception trace.
Mostly moving from warning to error for 500 status codes in logging and adding the exception trace to it.
This might cause duplicate logging for cases where an InternalError is thrown somewhere deeper but that seems better for now then missing an exception trace.
@blizzz We probably want to cleanup the way exceptions are handled there, I feel the generic InternalError is not very helpful there and could just be a generic Exception. Then we can catch and log all non-specific exceptions in the middleware or in one unified controller method. WDYT?

chore: Proper logs with error level and exception trace

---

.github/ISSUE_TEMPLATE/bug-report.yml.license
.github/ISSUE_TEMPLATE/feature-request.yml.license
.scripts/release.sh
LICENSES/CC-BY-SA-2.0.txt
LICENSES/LicenseRef-AppleAppStoreBadge.txt
LICENSES/LicenseRef-FacebookTrademarks.txt
LICENSES/LicenseRef-GooglePlayBadge.txt
LICENSES/LicenseRef-MastodonTrademarks.txt
LICENSES/LicenseRef-NextcloudTrademarks.txt
LICENSES/LicenseRef-XTrademarks.txt
REUSE.toml
appinfo/routes.php
build/fetch-material-icons.sh
tests/integration/run.sh

mostly covering `cypress/.../img` assets 
* Bad licenses: 0
* Deprecated licenses: 0
* Licenses without file extension: 0
* Missing licenses: 0
* Unused licenses: 0
* Used licenses: LicenseRef-MastodonTrademarks, LicenseRef-GooglePlayBadge, LicenseRef-XTrademarks, LicenseRef-AppleAppStoreBadge, CC-BY-SA-2.0, LicenseRef-NextcloudTrademarks, MIT, AGPL-3.0-or-later, LicenseRef-FacebookTrademarks, Apache-2.0
* Read errors: 0
* Files with copyright information: 806 / 1180
* Files with license information: 782 / 1180

Add SPDX header - Part 2

---

src/App.vue

The app menu selector changed, so we need these updates to when the table or application is active
Also added a check to avoid unnecessary  work when editing rows
Right now, all this is very hacky. Not sure if there's a better solution. Having `data-app-id` made this more robust, but that isn't available anymore
This gets rid of the console errors
```
NavigationTableItem.vue:134 [Vue warn]: Error in callback for watcher "$route": "TypeError: Cannot read properties of null (reading 'classList')"
```

fix: use different app menu selectors

---

src/modules/modals/CreateColumn.vue
src/modules/modals/CreateRow.vue

fixes https://github.com/nextcloud/tables/issues/1257

fix: only focus on input if modal is open

---

src/modules/modals/EditRow.vue

When editing a row with a single selection, part of it is hidden. This unhides it. 
Before:
After:

fix: unhide part of single selection NcSelect value

---

src/modules/main/sections/MainWrapper.vue

When opening a link like https://nextcloud.local/index.php/apps/tables/#/table/1/row/1 we should open the modal to edit the row directly. This was broken before as the element (table or view was not passed along while the modal component requires it).
Can also be reproduced by editing a row and just reloading the browser.

fix: Open row edit modal on initial load

---

css/modal.css
cypress/e2e/column-selection-multi.cy.js
cypress/e2e/column-selection.cy.js
cypress/e2e/column-text-line.cy.js
cypress/support/e2e.js
src/modules/modals/CreateColumn.vue
src/modules/modals/CreateContext.vue
src/modules/modals/CreateRow.vue
src/modules/modals/CreateTable.vue
src/modules/modals/EditColumn.vue
src/modules/modals/EditContext.vue
src/modules/modals/EditRow.vue
src/modules/modals/EditTable.vue
src/modules/modals/FileActionImport.vue
src/modules/modals/Import.vue
src/modules/modals/TransferContext.vue
src/modules/modals/TransferTable.vue

Fixes https://github.com/nextcloud/tables/issues/1213
Reviewers: please test `FileActionImport.vue` dialog, because i was not able to see it in UI
|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| ![Screenshot from 2024-07-25 18-42-30](https://github.com/user-attachments/assets/a574ae36-facf-482b-a914-affa839162f9) | ![Screenshot from 2024-07-25 18-46-24](https://github.com/user-attachments/assets/2390f327-2e97-4339-819a-3acc14246df8) |-------------|---------------------------------------------------------------|
| ![Screenshot from 2024-07-25 18-43-03](https://github.com/user-attachments/assets/c4e721dc-e2b1-46e7-8314-f4381c416dd8) | ![Screenshot from 2024-07-25 …

Migrate `NcModal` to `NcDialog`

---

cypress/e2e/tables-favorite.cy.js
src/modules/navigation/partials/NavigationTableItem.vue
src/shared/components/ncTable/sections/CustomTable.vue
src/shared/utils/displayError.js

Some small fixes I had included in another branch but are easier to get in separately, mostly found in sentry as reported through the js console:
- **fix: Add aria-label to pagination**
- **fix: Fix missing actions for empty default slot**
- **fix: Proper evaluation order when building errors strings**

Fix console warnings and errors

---

cypress/e2e/column-text-link.cy.js
cypress/support/commands.js
src/modules/sidebar/sections/SidebarIntegration.vue
src/shared/components/ncTable/partials/rowTypePartials/TextLinkForm.vue
src/shared/mixins/copyToClipboard.js

When no link provider (except URL) is enabled a multiselect field might be confusing to users, so this PR switches over to a simple input field in that case. As there are no suggestions then a multiselect does not make sense.
- In addition I added a copy and open link button to make it easier to access the link again (fixes https://github.com/nextcloud/tables/issues/1186)
- Move clipboard logic into a mixin so it can be reused
- Render a link preview in the edit modal
Styling of the multiselect is still a bit odd, but will check that separately as it seems to come from the component library.
[Kapture 2024-08-22 at 15.54.06.webm](https://github.com/user-attachments/assets/ced0c6dd-5f13-4ca1-9a61-ac76ff63eaa4)

feat: Use simple input field instead of multiselect for plain URLs

---

package-lock.json

This audit fix resolves 10 of the total 12 vulnerabilities found in your project.
* [@vue/component-compiler-utils](#user-content-\@vue\/component-compiler-utils)
* [axios](#user-content-axios)
* [braces](#user-content-braces)
* [elliptic](#user-content-elliptic)
* [fast-xml-parser](#user-content-fast-xml-parser)
* [micromatch](#user-content-micromatch)
* [postcss](#user-content-postcss)
* [vue-loader](#user-content-vue-loader)
* [webpack](#user-content-webpack)
* [ws](#user-content-ws)
* Caused by vulnerable dependency:
* [postcss](#user-content-postcss)
* Affected versions: *
* Package usage:
* `node_modules/@vue/component-compiler-utils`
* Server-Side Request Forgery in axios
* Severity: **high**
* Reference: [https://github.com/advisories/GHSA-8hc4-vh64-cxmj](https://github.com/advisor …

[stable0.7] Fix npm audit

---

src/shared/components/ncTable/mixins/columnClass.js

fix: check sorting array is non-empty

---

.github/workflows/cypress-custom.yml

actions/upload-artifact v2 is deprecated and causes failures: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

fix: use actions/upload-artifact v4 for cypress workflow

---

cypress/e2e/tables-table.cy.js

We do not need to check if the modal content is visible. When we have this, we sometimes get the following error:
```
AssertionError: Timed out retrying after 4000ms: expected '<div.modal__content>' to be 'visible'
This element `<div.modal__content>` is not visible because it has CSS property: `position: fixed` and it's being covered by another element:
`<div data-v-1d602fb0="" class="modal-wrapper modal-wrapper--normal">...</div>`
```

fix(Cypress): remove unneeded visibility check

---

appinfo/routes.php
lib/Controller/Api1Controller.php
lib/Controller/Errors.php
lib/Controller/ImportController.php
lib/Controller/RowController.php
lib/Model/RowDataInput.php
lib/Service/ImportService.php
lib/Service/RowService.php
lib/Service/ViewService.php
openapi.json
src/modules/modals/CreateRow.vue
src/store/data.js
src/types/openapi/openapi.ts
tests/integration/features/APIv1.feature
tests/integration/features/APIv2.feature
tests/integration/features/bootstrap/FeatureContext.php

includes
- a fix of the RowDataInput – has to be iterable, otherwise values were stored empty :see_no_evil: 
- and a fix to accept selection-type values with the rows ocs endpoint
- and extended tests

refactor(Rows): switch front-end to use Row OCS API 

---

.github/workflows/cypress-custom.yml
cypress/e2e/tables-table.cy.js

At https://github.com/nextcloud/tables/actions/runs/11089354255?pr=1396, we have the error `Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run`. This is an attempt to fix it.

fix: use unique names for actions upload-artifact

---

lib/Controller/Api1Controller.php
lib/Controller/ApiColumnsController.php
lib/Controller/ApiFavoriteController.php
lib/Controller/ApiGeneralController.php
lib/Controller/ApiTablesController.php
lib/Controller/ColumnController.php
lib/Controller/ContextController.php
lib/Controller/ImportController.php
lib/Controller/PageController.php
lib/Controller/RowController.php
lib/Controller/SearchController.php
lib/Controller/ShareController.php
lib/Controller/TableController.php
lib/Controller/TableTemplateController.php
lib/Controller/ViewController.php
lib/Middleware/PermissionMiddleware.php
tests/integration/features/APIv2.feature

Use the permission middleware in more places (I did not remove the service-level checks though) and remove depracted use of annotations towards attributes.

refactor: Extend Permission Middleware usage and replace deprecated annotations with attributes

---

package-lock.json

This audit fix resolves 16 of the total 18 vulnerabilities found in your project.
* [@nextcloud/dialogs](#user-content-\@nextcloud\/dialogs)
* [@nextcloud/files](#user-content-\@nextcloud\/files)
* [@nextcloud/l10n](#user-content-\@nextcloud\/l10n)
* [@nextcloud/moment](#user-content-\@nextcloud\/moment)
* [@nextcloud/vue](#user-content-\@nextcloud\/vue)
* [@vue/component-compiler-utils](#user-content-\@vue\/component-compiler-utils)
* [body-parser](#user-content-body-parser)
* [cookie](#user-content-cookie)
* [dompurify](#user-content-dompurify)
* [express](#user-content-express)
* [node-gettext](#user-content-node-gettext)
* [path-to-regexp](#user-content-path-to-regexp)
* [postcss](#user-content-postcss)
* [send](#user-content-send)
* [serve-static](#user-content-serve-static)
* …

[stable0.8] Fix npm audit

---

lib/Service/RowService.php
tests/integration/features/APIv2.feature
tests/integration/features/bootstrap/CollectionManager.php
tests/integration/features/bootstrap/FeatureContext.php

The fixes include a few cases were `500` was returned, where `403` was expected, and also where it should be `404`.
These were all found when writing the missing tests – the fifth batch – for #1006.
Closes #1006

fix return status in a few cases and add integration tests against content modification through Applications

---

lib/Controller/ApiTablesController.php

currently an import fails silently (no web UI feedback) with `Argument #15 ($selectionOptions) must be of type ?string, array given` in the logs. This fixes handlig of the selectionOptions.

fix(Import): expect selectionOptions as array from json

---

.devcontainer/devcontainer.json

Fixes #1392 
Thanks to @MI-KY for doing the fix at https://github.com/nextcloud/tables/pull/1393

fix: Use devcontainer with php v8.2

---

src/shared/components/ncTable/partials/TableCellHtml.vue

Fixes https://github.com/nextcloud-gmbh/h1/issues/833
Initially reviewed at https://github.com/nextcloud-gmbh/tables/pull/5

enh: use tiptap's editor to render HTML

---

cypress/e2e/column-number-progress.cy.js
src/shared/components/ncTable/partials/columnTypePartials/forms/NumberProgressForm.vue
src/shared/components/ncTable/partials/rowTypePartials/NumberProgressForm.vue

At the moment, it is possible to to keep reducing to negative numbers or above 100, as seen below. 
https://github.com/user-attachments/assets/282424e6-9e54-4b84-a72e-1959dc378a2a
This PR  fixes it.

fix: ensure number progress stays within 1-100 range

---

lib/Service/ColumnTypes/TextLinkBusiness.php

fixes #1442 
https://github.com/user-attachments/assets/8a89c889-a1a4-4e80-a025-8b294db22aeb
https://github.com/user-attachments/assets/28dc5e97-c480-476d-b1d9-b5cf786855e2
TODO:

fix: use actual providerId in link rows

---

src/shared/components/ncTable/mixins/columnsTypes/numberProgress.js

fix: use 0 for falsy number progress values during sorting

---

cypress/support/commands.js

Server changed at https://github.com/nextcloud/server/pull/49560, so tests are failing. The ideal solution is to update  @nextcloud/cypress to benefit from https://github.com/nextcloud-libraries/nextcloud-cypress/pull/703, but doing this gives ResizeObserver errors. This is a temporary fix while we figure out how to fix that

ci: Hotfix to make login work as long as we are on older cypress version

---

src/modules/modals/Import.vue

Right now, at https://github.com/nextcloud/tables/issues/1440, when the import fails, there's no error visible to the user. So, this adds an error popup so the user knows that there was a problem

enh: display error popup when import preview fails

---

lib/Db/Column.php
lib/Service/ViewService.php
tests/integration/features/APIv1.feature
tests/integration/features/bootstrap/FeatureContext.php

Regression was introduced in https://github.com/nextcloud/tables/commit/94da27afcb6aaddf01ab7b00d9f353ea2fba04bb#diff-94c64cbe53bdc638784b9674d36ee5fdb26835b2c4a5b421195dd18711b48349 – the check was a little too strict now.
(partially) fixes #1499

fix: allow adding meta data columns to views again

---

lib/Capabilities.php
lib/Constants/ShareReceiverType.php
lib/Db/LegacyRowMapper.php
lib/Db/RowCellMapperSuper.php
lib/Db/Share.php
lib/Db/ShareMapper.php
lib/Helper/CircleHelper.php
lib/Helper/UserHelper.php
lib/Middleware/PermissionMiddleware.php
lib/Service/PermissionsService.php
lib/Service/ShareService.php
openapi.json
package-lock.json
package.json
src/modules/sidebar/mixins/shareAPI.js
src/modules/sidebar/partials/ShareForm.vue
src/modules/sidebar/partials/ShareList.vue
src/shared/mixins/searchUserGroup.js
src/shared/mixins/shareTypesMixin.js
src/shared/modals/DialogConfirmation.vue
src/types/openapi/openapi.ts
tests/unit/Service/PermissionsServiceTest.php

share with teams

---

appinfo/routes.php
cypress/e2e/context.cy.js
lib/Controller/NavigationController.php
lib/Db/ContextMapper.php
lib/Db/ContextNavigationMapper.php
lib/Listener/BeforeTemplateRenderedListener.php
lib/Service/ContextService.php
lib/Service/ShareService.php
openapi.json
src/modules/modals/CreateContext.vue
src/modules/modals/EditContext.vue
src/modules/navigation/partials/NavigationContextItem.vue
src/service/rebuild-navigation.js
src/shared/constants.js
src/store/store.js
tests/psalm-baseline.xml

Part of https://github.com/nextcloud/tables/issues/1177 and https://github.com/nextcloud/tables/pull/1193
Todo

feat: Add UI elements to modify navigation display

---

lib/Service/ViewService.php

- meta columns included in sorting do not need to be hidden from the response
- changed the return value to an empty array, to avoid a Vue error in the frontend (it expects an array)
Now however, for owners the sorting is working ~~,but for share recipients it is not (but the content is at least visible).~~
~~Not sure this is the best approach, and the sorting needs frontend changes as well. Hoping for your feedback @enjeck~~
addresses #1524

fix(Views): allow to sort for meta columns

---

appinfo/routes.php
cypress/e2e/context.cy.js
lib/Controller/NavigationController.php
lib/Db/ContextMapper.php
lib/Db/ContextNavigationMapper.php
lib/Listener/BeforeTemplateRenderedListener.php
lib/Service/ContextService.php
lib/Service/ShareService.php
openapi.json
src/modules/modals/CreateContext.vue
src/modules/modals/EditContext.vue
src/modules/navigation/partials/NavigationContextItem.vue
src/service/rebuild-navigation.js
src/shared/constants.js
src/store/store.js
tests/psalm-baseline.xml

contributes to #1177
It was temporarily disabled and shown by default as we did not have web UI controls to configure it.

feat(Contexts): enable nav bar display logic

---

lib/Db/RowCellMapperSuper.php
lib/Db/RowCellSelectionMapper.php
lib/Db/RowCellUsergroupMapper.php

I war running today into this exception:
<details><summary>OCA\\Tables\\Db\\RowCellMapperSuper::filterValueToQueryParam(): Argument #2 ($value) must be of type string|float, null given, called in /path/to/nextcloud/apps-repos/tables/lib/Db/Row2Mapper.php on line 866 in file '/path/to/nextcloud/apps-repos/tables/lib/Db/RowCellMapperSuper.php' line 47</summary>
```json
{
"reqId": "J0E9GurC2VQmwSVeG9Dx",
"level": 3,
"time": "2025-01-10T14:50:48+00:00",
"remoteAddr": "127.0.0.1",
"user": "master",
"app": "index",
"method": "GET",
"url": "/index.php/apps/tables/table",
"message": "OCA\\Tables\\Db\\RowCellMapperSuper::filterValueToQueryParam(): Argument #2 ($value) must be of type string|float, null given, called in /path/to/nextcloud/apps-repos/tables/lib/Db/Row2Mapper.php on line 866 in file …
```

fix(RowMappers): value might at least be null

---

lib/Service/FavoritesService.php

fixes #1350 
The data was stored correctly, but the retrieval was borked.

fix(Favorites): repair runtime cache population

---

src/shared/components/ncTable/partials/TableCellUsergroup.vue

We need to wrap the container of usergroup items. Otherwise, they overflow the container when there are too many items.

fix: wrap usergroup's cell values

---

composer.json
composer.lock

Fixes errors like `{"reqId":"0CPERio4AlczGp0fMWbK","level":3,"time":"2025-01-26T10:40:37+00:00","remoteAddr":"127.0.0.1","user":"user1","app":"PHP","method":"MOVE","url":"/remote.php/webdav/test/move-coll-dst1","message":"Declaration of Psr\\Log\\AbstractLogger::emergency($message, array $context = []) must be compatible with Psr\\Log\\LoggerInterface::emergency(Stringable|string $message, array $context = []): void at /home/jld3103/src/github.com/nextcloud/server/apps/tables/vendor/psr/log/Psr/Log/AbstractLogger.php#22","userAgent":"Dart/3.6 (dart:io)","version":"32.0.0.0","data":{"app":"PHP"}}`.
I don't know why it is triggered by WebDAV :woman_shrugging:
This is just the steps from the Engineering mailing list on 14.10.2024.

chore(dev-deps): Bump nextcloud/ocp package

---

cypress/e2e/tables-archive.cy.js
cypress/e2e/tables-export-csv.cy.js
cypress/e2e/tables-favorite.cy.js
cypress/e2e/tables-fe-filters.cy.js
cypress/e2e/tables-import.cy.js
cypress/e2e/tables-rows.cy.js
cypress/support/commands.js
lib/Service/TableService.php
lib/Service/TableTemplateService.php

solves #1528 
"Nextcloud" is variable with the instance name, as it should be. I have kept Nextcloud though in the link description towards the Tables wiki. Could remove it generally if it makes sense.

feat(Templates): extend the tutorial table

---

.github/workflows/npm-audit-fix.yml
renovate.json

- removes stable0.7 from npm-audit, the series is EOL
- adds PHP dependency updates to renovate
- adds workflow updates to renovate
- adds stable0.8 as target branch to renovate
- removes stable0.7 (EOL) as target branch to renovate
I am not familiar much with renovate config and took looks at the configs at some other apps :crossed_fingers:

ci(config): stop updates for 0.7, enable PHP updates in renovate

---

.github/workflows/integration.yml
tests/integration/features/APIv1.feature
tests/integration/features/APIv2.feature

they were not running previously: https://github.com/nextcloud/tables/actions/workflows/integration.yml

ci: fix integration yaml syntax

---

lib/Db/Row2Mapper.php

- IQueryBuilder::orderBy() replaces an existing order instead of appending to it
This should tame flaky mysql tests integration tests against ordering with multiple columns (e.g. [here](https://github.com/nextcloud/tables/actions/runs/13319475646/job/37201145029?pr=1409) or [here](https://github.com/nextcloud/tables/actions/runs/13319475646/job/37201143683?pr=1409) or [here](https://github.com/nextcloud/tables/actions/runs/13318834183/job/37199217874))

fix(sort): use addOrderBy for sorting with multiple columns

---

lib/Db/Column.php
lib/Db/LegacyRowMapper.php
lib/Db/Row2.php
lib/Db/Row2Mapper.php
lib/Helper/ColumnsHelper.php
lib/Model/RowDataInput.php
lib/Service/RowService.php
tests/integration/features/APIv1.feature
tests/integration/features/bootstrap/FeatureContext.php
tests/unit/Service/LegacyRowMapperTest.php

First attempt to improve #638 by applying exact view filters as a default value for new rows

fix: Properly create new rows in filtered views

---

lib/Db/Column.php
lib/Service/ImportService.php
tests/integration/features/APIv1.feature
tests/integration/resources/import-from-libreoffice-optional-fields.csv
tests/integration/resources/import-from-libreoffice-optional-fields.csv.license

- do not try to pass `null` to DateTimeImmutable as it would cause an Exception
- be stricter on small letter-only values that might be turned into a DateTimeImmutable object because they match with timezone abbreviations
- do not consider pure numbers a date
fixes #1518

fix(Import): DateTime import fixes

---

src/modules/modals/CreateRow.vue
src/modules/modals/EditRow.vue
src/shared/components/ncTable/mixins/rowHelper.js
src/shared/constants.js

We want to only allow certain protocols for the text link field. For now, just http and https.
Error when an invalid protocol is entered looks like this, and you're unable to save:

enh: Restrict text link protocols

---

lib/Service/RowService.php

When create view with filter
when adding new records, I get an error
```
An internal error or exception occurred: OCA\\Tables\\Service\\RowService - create: OCA\\Tables\\Db\\Row2Mapper - insertCell: Can not insert cell, because the given column-id is not known
```
this PR fixes this bug

fix: fix creation failure when using creator filter

---

src/modules/main/sections/View.vue
src/modules/modals/ViewSettings.vue

There is a column `description` in database and BE part is ready to store it. But for some reason its not used on FE side.
<details><summary>:mag: Preview</summary>
<p>
</p>
</details>

Enhancement: Add description field for views

---

src/modules/modals/CreateRow.vue
src/modules/modals/EditRow.vue
src/shared/components/ncTable/partials/rowTypePartials/RowFormWrapper.vue

- Realign "expand" icon for rich text in the "create row" modal
- Wrap column description text to avoid overflow
- Resizes "edit row" modal since it was too large

enhancement: UI fixes for create/edit row dialogs

---

lib/Analytics/AnalyticsDatasource.php

Analytics App:
normal ->getData does not deliver any values for numbers with just default values.
the default number will be delivered in that case to the Analytics data source

Analytics: get default values for number columns

---

src/modules/sidebar/partials/ShareList.vue

If an avatar is not set individually, it will already create one based on the displayname. It is nothing we have to take care of here.
Fixes #1723

fix(UI): fetch avatar correctly by user id

---

src/modules/modals/ImportPreview.vue

Right now we have duplicated `getColumnsFromBE` import: in computed and in actions. Let's keep actions only

Fix: computed property duplicates action on import

---

lib/Db/Row2Mapper.php
lib/Db/RowCellMapperSuper.php

fixes #1558 
When a usergroup field has multiple values, each is saved as a separate row in the `oc_tables_row_cells_usergroup`. So, when we want to update a a field, we should delete all previous values and insert to avoid duplicates. Problem was, we were assuming that the row only has one usergroup column, so we were deleting all usergroup cells for that row. But when there are multiple usergroup columns, only the last is kept since others are deleting. Instead, we should be deleting based on the row and column, not just the row.

fix: Properly update usergroup cells

---

src/shared/components/ncTable/mixins/rowHelper.js

fixes #1761 
For an empty link field, we should return `true` when checking if the field has a valid URL protocol. Otherwise, even for non-mandatory fields, the "Save" button is not clickable if no input is provided.

fix: avoid marking empty link fields as invalid protocol

---

cypress/e2e/context-navigation.cy.js
cypress/support/commands.js
src/pages/Context.vue

tests(Cypress): add tests for Application navigation display

---

lib/Db/TableMapper.php
lib/Db/ViewMapper.php
lib/Service/PermissionsService.php
lib/Service/ViewService.php
tests/integration/features/APIv1.feature
tests/integration/features/bootstrap/FeatureContext.php

fix(Permissions): view permissions inherit from table permissions

---

tests/unit/bootstrap.php

This uses the new tests/autoload.php from nextcloud/server instead of messing directly with OC private autoloader.
See https://github.com/nextcloud/server/pull/52951 and https://github.com/nextcloud/server/pull/52945 for context.

chore(tests): Cleanup bootstrap.php to be forward-compatible

---

src/App.vue

Instead of calling some initial request sequentially, we parallelize the calls. As a result, we save >1 second during the initial load

perf: Parallelize initial requests

---

.github/workflows/integration.yml

Currently we have to force merge on non-PHP changes, because integration-summary does not run. This is supposed to fix it.

ci: unblock integration test on irrelevant changes

---

src/modules/sidebar/partials/ShareInternalLink.vue
src/modules/sidebar/sections/SidebarSharing.vue

This PR introduces a new sharing option component called "Internal Link", which allows users to copy a direct link to the currently selected table or view. This feature is useful for quickly sharing internal resources with users who already have access to the folder.
Features:
- New ShareInternalLink.vue component
- Displays an icon, title, and description for internal links
- Includes a copy-to-clipboard button using NcActionButton and ContentCopy icon
- Localized (t('tables', ...)) and translations for English and German added

 Add "Internal Link" Sharing Tile with Copy-to-Clipboard

---

src/shared/components/ncTable/mixins/columnsTypes/selection.js
src/shared/components/ncTable/mixins/filter.js

I think this filter will improve the UX. Because now you don't have to remember the exact value.

feat: Enhance "Contains" filter to support "selection" type

---

lib/Analytics/AnalyticsDatasource.php
lib/Api/V1Api.php
lib/Command/Clean.php
lib/Command/TransferLegacyRows.php
lib/Controller/Api1Controller.php
lib/Migration/NewDbStructureRepairStep.php
lib/Service/ColumnService.php
lib/Service/TableService.php
lib/Service/ViewService.php

- simply this method, kill a lot of `null`s in the majority of the calls
- add a destinct method to cover the edge case
- improves clarity
rebased on the workflow update for testing

[stable0.8] refactor: simplify Columns::findAllByTable method

---

lib/Service/ImportService.php

In such a case, or when the cells are empty, there will be a "Undefined array key "

fix: add check for column index existence before processing

---

cypress/e2e/entity-not-found.cy.js
src/App.vue
src/modules/main/partials/ErrorMessage.vue
src/pages/Context.vue
src/pages/Table.vue
src/pages/View.vue
src/shared/utils/displayError.js
src/store/store.js

This PR improves error handling when navigating to non-existent tables, views, or contexts in the Tables app.
Previously, accessing a non-existent resource (e.g. /view/999 or /context/999) would result in an unhandled exception (TypeError: undefined) and show only a loading spinner. This was confusing to users and cluttered the console with errors.
- Added proper error catching in Table.vue, View.vue, and Context.vue
- Display a user-friendly error message and icon when a resource is not found (404)
- Ensured layout is visually centered and styled consistently with other apps (e.g. Deck)

1296 infinite loading when visiting non existent application

---

.github/workflows/integration.yml

- every now and then we see the error: cat: /home/runner/work/tables/tables/query.log: No such file or directory
- also count the query log properly, as a single query may span multiple lines

ci: reduce assumptions about paths on the ci host
